"""Planner for the user-facing Abaqus/CAE Copilot."""

from __future__ import annotations

import json
import re
import subprocess
import uuid
from pathlib import Path
from typing import Any

from .models import CopilotAction, CopilotExecutionResult, CopilotPlan

ROOT = Path(__file__).resolve().parent.parent
CODEX_CLIENT = Path(__file__).with_name("codex_app_server_client.mjs")


class CodexUnavailable(RuntimeError):
    """Raised when local Codex app-server cannot produce a plan."""


def build_copilot_plan(text: str, *, backend: str = "codex") -> CopilotPlan:
    clean_text = text.strip()
    if not clean_text:
        raise ValueError("请输入 Abaqus 建模需求")
    session_id = f"copilot-{uuid.uuid4().hex[:8]}"
    if backend == "template":
        return _template_plan(clean_text, session_id=session_id, raw="")
    try:
        assistant_text = _call_codex(clean_text)
        payload = _extract_json_object(assistant_text)
        return _plan_from_payload(payload, clean_text, session_id, assistant_text)
    except (CodexUnavailable, ValueError, json.JSONDecodeError, subprocess.SubprocessError):
        if backend == "codex_strict":
            raise
        return _template_plan(clean_text, session_id=session_id, raw="")


def execute_plan(plan: CopilotPlan, *, bridge_mode: str = "mock") -> CopilotExecutionResult:
    action_lines = []
    timeline = []
    for index, action in enumerate(plan.actions, start=1):
        action_lines.append(f"# Action {index}: {action.title}")
        action_lines.append(_python_for_action(action))
        action_lines.append("")
        timeline.append(
            {
                "status": "done" if bridge_mode == "mock" else "queued",
                "title": action.title,
                "detail": action.rationale or action.action,
            }
        )
    out_dir = Path("artifacts") / "copilot" / plan.session_id
    out_dir.mkdir(parents=True, exist_ok=True)
    script_path = out_dir / "abaqus_copilot_actions.py"
    script_path.write_text(
        "\n".join(
            [
                "# Generated by AbaqusAgent Copilot MVP.",
                "# -*- coding: utf-8 -*-",
                "# Safe deterministic script rendered from white-listed Copilot actions.",
                "",
                *action_lines,
            ]
        ),
        encoding="utf-8",
    )
    status = "mock_executed" if bridge_mode == "mock" else "real_bridge_pending"
    return CopilotExecutionResult(
        session_id=plan.session_id,
        status=status,
        bridge_mode="mock" if bridge_mode == "mock" else "abaqus_plugin",
        script_path=str(script_path),
        timeline=timeline,
        user_visible_summary=(
            "已把自然语言需求转换成 Abaqus/CAE 可执行动作。"
            if bridge_mode != "mock"
            else "本机未确认真实 Abaqus 会话，已完成本地模拟执行并生成 Abaqus Python 脚本。"
        ),
        next_step=(
            "在 Abaqus/CAE 插件中连接本地服务后执行队列。"
            if bridge_mode != "mock"
            else "打开生成脚本检查建模动作；有真实 Abaqus 后可切到插件桥执行。"
        ),
    )


def _call_codex(user_text: str) -> str:
    prompt = f"""你是 Abaqus/CAE Copilot 的动作规划器。用户是土木/机械仿真新手，需要你把自然语言变成安全的 Abaqus 建模动作。

只允许输出一个 JSON 对象，不要 markdown，不要解释。
JSON schema:
{{
  "intent": "string",
  "user_summary": "中文一句话",
  "model_type": "cantilever",
  "needs_clarification": false,
  "clarification_questions": [],
  "actions": [
    {{
      "action": "create_cantilever_model",
      "title": "中文短标题",
      "rationale": "为什么这么做",
      "params": {{"length_mm": 200, "height_mm": 20, "width_mm": 20, "material": "steel"}},
      "abaqus_python": "安全的 Abaqus Python 片段；可以是注释级 MVP，不要访问网络/文件删除/任意系统命令"
    }}
  ],
  "expected_outputs": ["最大位移", "最大 Mises 应力"],
  "safety_notes": ["执行前请确认单位"]
}}

白名单 action 只能是:
- create_cantilever_model
- apply_boundary_condition
- submit_job_or_prepare_run

如果用户缺关键几何/载荷信息，可以用合理默认值，但要在 safety_notes 说明。

用户需求:
{user_text}
"""
    proc = subprocess.run(
        ["node", str(CODEX_CLIENT), "--cwd", str(ROOT), "--prompt", prompt],
        cwd=ROOT,
        text=True,
        capture_output=True,
        timeout=140,
        check=False,
    )
    if proc.returncode != 0:
        detail = proc.stderr.strip() or proc.stdout.strip() or "codex app-server failed"
        raise CodexUnavailable(detail)
    try:
        envelope = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise CodexUnavailable(proc.stdout[:1000]) from exc
    assistant_text = str(envelope.get("assistantText") or "").strip()
    if not assistant_text:
        raise CodexUnavailable("Codex returned empty assistantText")
    return assistant_text


def _extract_json_object(text: str) -> dict[str, Any]:
    cleaned = text.strip()
    if cleaned.startswith("```"):
        cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
        cleaned = re.sub(r"\s*```$", "", cleaned)
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start < 0 or end < start:
        raise ValueError("Codex response did not contain a JSON object")
    return json.loads(cleaned[start : end + 1])


def _plan_from_payload(
    payload: dict[str, Any],
    user_text: str,
    session_id: str,
    raw: str,
) -> CopilotPlan:
    actions = []
    for item in payload.get("actions") or []:
        if not isinstance(item, dict):
            continue
        try:
            action = CopilotAction(**item)
            action.abaqus_python = _python_for_action(action)
            actions.append(action)
        except ValueError:
            continue
    if not actions:
        actions = _template_actions(user_text)
    return CopilotPlan(
        session_id=session_id,
        backend="codex_app_server",
        intent=str(payload.get("intent") or "create_abaqus_model"),
        user_summary=str(payload.get("user_summary") or user_text),
        model_type=str(payload.get("model_type") or "cantilever"),
        needs_clarification=bool(payload.get("needs_clarification") or False),
        clarification_questions=list(payload.get("clarification_questions") or []),
        actions=actions,
        expected_outputs=list(payload.get("expected_outputs") or ["最大位移", "最大 Mises 应力"]),
        safety_notes=list(payload.get("safety_notes") or []),
        assistant_message=_assistant_message(actions),
        raw_assistant_text=raw,
    )


def _template_plan(text: str, *, session_id: str, raw: str) -> CopilotPlan:
    actions = _template_actions(text)
    return CopilotPlan(
        session_id=session_id,
        backend="template",
        intent="create_abaqus_model",
        user_summary="建立一个悬臂梁静力分析模型，并准备查看端部位移和最大应力。",
        model_type="cantilever",
        actions=actions,
        expected_outputs=["端部最大位移", "最大 Mises 应力", "求解日志是否报错"],
        safety_notes=["模板模式使用默认尺寸和材料；真实项目执行前请确认单位、截面和载荷。"],
        assistant_message=_assistant_message(actions),
        raw_assistant_text=raw,
    )


def _template_actions(text: str) -> list[CopilotAction]:
    dims = _infer_dimensions(text)
    return [
        CopilotAction(
            action="create_cantilever_model",
            title="创建悬臂梁几何与材料",
            rationale="先建立一个用户能看见的梁模型，材料默认钢材，单位按 mm-N-MPa 处理。",
            params=dims | {"material": "steel"},
            abaqus_python=_create_cantilever_python(dims),
        ),
        CopilotAction(
            action="apply_boundary_condition",
            title="固定左端并在右端施加载荷",
            rationale="悬臂梁最常见入门工况，用户可以直接观察端部下挠。",
            params={"fixed_face": "left", "force_n": 100, "direction": "downward_y"},
            abaqus_python=_boundary_load_python({"force_n": 100}),
        ),
        CopilotAction(
            action="submit_job_or_prepare_run",
            title="准备作业并说明结果查看方式",
            rationale="创建作业、提交求解并把最大位移/最大 Mises 写入结果 JSON。",
            params={"job_name": "Copilot_Cantilever_Job", "run_policy": "submit_and_extract"},
            abaqus_python=_submit_and_extract_python({"job_name": "Copilot_Cantilever_Job"}),
        ),
    ]


def _infer_dimensions(text: str) -> dict[str, int]:
    numbers = [int(value) for value in re.findall(r"\d+", text)]
    return {
        "length_mm": numbers[0] if len(numbers) >= 1 else 200,
        "height_mm": numbers[1] if len(numbers) >= 2 else 20,
        "width_mm": numbers[2] if len(numbers) >= 3 else 20,
    }


def _assistant_message(actions: list[CopilotAction]) -> str:
    titles = "、".join(action.title for action in actions)
    return f"我会按 {len(actions)} 步操作 Abaqus：{titles}。你确认后我再执行。"


def _python_for_action(action: CopilotAction) -> str:
    if action.action == "create_cantilever_model":
        return _create_cantilever_python(action.params)
    if action.action == "apply_boundary_condition":
        return _boundary_load_python(action.params)
    return _submit_and_extract_python(action.params)


def _create_cantilever_python(params: dict[str, Any]) -> str:
    length = float(params.get("length_mm", 200) or 200)
    height = float(params.get("height_mm", 20) or 20)
    width = float(params.get("width_mm", 20) or 20)
    return (
        "from abaqus import *\n"
        "from abaqusConstants import *\n"
        "from odbAccess import openOdb\n"
        "import json\n"
        "import mesh\n"
        "COPILOT_MODEL_NAME = 'Copilot_Cantilever'\n"
        "COPILOT_PART_NAME = 'Beam'\n"
        "COPILOT_INSTANCE_NAME = 'Beam-1'\n"
        f"COPILOT_LENGTH = {length:.6f}\n"
        f"COPILOT_HEIGHT = {height:.6f}\n"
        f"COPILOT_WIDTH = {width:.6f}\n"
        "if COPILOT_MODEL_NAME in mdb.models.keys():\n"
        "    del mdb.models[COPILOT_MODEL_NAME]\n"
        "model = mdb.Model(name=COPILOT_MODEL_NAME)\n"
        "sketch = model.ConstrainedSketch(name='beam_profile', sheetSize=max(500.0, COPILOT_LENGTH * 2.0))\n"
        "sketch.rectangle(point1=(0.0, -COPILOT_HEIGHT / 2.0), point2=(COPILOT_LENGTH, COPILOT_HEIGHT / 2.0))\n"
        "part = model.Part(name=COPILOT_PART_NAME, dimensionality=THREE_D, type=DEFORMABLE_BODY)\n"
        "part.BaseSolidExtrude(sketch=sketch, depth=COPILOT_WIDTH)\n"
        "material = model.Material(name='Steel')\n"
        "material.Elastic(table=((210000.0, 0.3),))\n"
        "model.HomogeneousSolidSection(name='SteelSection', material='Steel')\n"
        "all_cells = part.Set(cells=part.cells[:], name='ALL_CELLS')\n"
        "part.SectionAssignment(region=all_cells, sectionName='SteelSection')\n"
        "part.seedPart(size=max(2.0, COPILOT_HEIGHT / 2.0), deviationFactor=0.1, minSizeFactor=0.1)\n"
        "part.setElementType(regions=(part.cells[:],), elemTypes=(mesh.ElemType(elemCode=C3D8R, elemLibrary=STANDARD),))\n"
        "part.generateMesh()\n"
        "assembly = model.rootAssembly\n"
        "assembly.DatumCsysByDefault(CARTESIAN)\n"
        "assembly.Instance(name=COPILOT_INSTANCE_NAME, part=part, dependent=ON)\n"
        "model.StaticStep(name='LoadStep', previous='Initial', nlgeom=OFF)\n"
    )


def _boundary_load_python(params: dict[str, Any]) -> str:
    load = abs(float(params.get("force_n", params.get("load_n", 100)) or 100))
    return (
        "model = mdb.models[COPILOT_MODEL_NAME]\n"
        "assembly = model.rootAssembly\n"
        "inst = assembly.instances[COPILOT_INSTANCE_NAME]\n"
        "tol = 1.0e-3\n"
        "left_faces = inst.faces.getByBoundingBox(xMin=-tol, xMax=tol)\n"
        "if len(left_faces) == 0:\n"
        "    raise RuntimeError('Copilot could not find the left fixed face')\n"
        "assembly.Set(faces=left_faces, name='LEFT_FIXED_FACE')\n"
        "model.EncastreBC(name='BC_Left_Fixed', createStepName='Initial', region=assembly.sets['LEFT_FIXED_FACE'])\n"
        "load_nodes = inst.nodes.getByBoundingBox(\n"
        "    xMin=COPILOT_LENGTH - tol,\n"
        "    xMax=COPILOT_LENGTH + tol,\n"
        "    yMin=-tol,\n"
        "    yMax=tol,\n"
        "    zMin=COPILOT_WIDTH / 2.0 - tol,\n"
        "    zMax=COPILOT_WIDTH / 2.0 + tol,\n"
        ")\n"
        "if len(load_nodes) == 0:\n"
        "    load_nodes = inst.nodes.getByBoundingBox(xMin=COPILOT_LENGTH - tol, xMax=COPILOT_LENGTH + tol)\n"
        "if len(load_nodes) == 0:\n"
        "    raise RuntimeError('Copilot could not find right-end load nodes')\n"
        "assembly.Set(nodes=(load_nodes[0:1]), name='RIGHT_LOAD_NODE')\n"
        f"model.ConcentratedForce(name='Load_100N_Down', createStepName='LoadStep', region=assembly.sets['RIGHT_LOAD_NODE'], cf2=-{load:.6f})\n"
    )


def _submit_and_extract_python(params: dict[str, Any]) -> str:
    job_name = str(params.get("job_name") or "Copilot_Cantilever_Job")
    return (
        f"COPILOT_JOB_NAME = '{job_name}'\n"
        "if COPILOT_JOB_NAME in mdb.jobs.keys():\n"
        "    del mdb.jobs[COPILOT_JOB_NAME]\n"
        "mdb.Job(name=COPILOT_JOB_NAME, model=COPILOT_MODEL_NAME, description='AbaqusAgent Copilot real smoke')\n"
        "mdb.saveAs(pathName=COPILOT_JOB_NAME + '.cae')\n"
        "mdb.jobs[COPILOT_JOB_NAME].submit(consistencyChecking=ON)\n"
        "mdb.jobs[COPILOT_JOB_NAME].waitForCompletion()\n"
        "odb = openOdb(COPILOT_JOB_NAME + '.odb')\n"
        "frame = odb.steps['LoadStep'].frames[-1]\n"
        "u_values = frame.fieldOutputs['U'].values\n"
        "s_values = frame.fieldOutputs['S'].values\n"
        "max_u = max([v.magnitude for v in u_values]) if u_values else None\n"
        "max_mises = max([v.mises for v in s_values]) if s_values else None\n"
        "odb.close()\n"
        "result = {\n"
        "    'job_name': COPILOT_JOB_NAME,\n"
        "    'status': 'COMPLETED',\n"
        "    'max_displacement': max_u,\n"
        "    'max_mises': max_mises,\n"
        "    'model': COPILOT_MODEL_NAME,\n"
        "}\n"
        "with open(COPILOT_JOB_NAME + '_copilot_result.json', 'w') as f:\n"
        "    json.dump(result, f, indent=2, sort_keys=True)\n"
        "print('ABAQUS_AGENT_COPILOT_RESULT ' + json.dumps(result, sort_keys=True))\n"
    )


def cli_probe() -> int:
    plan = build_copilot_plan("建一个悬臂梁，左端固定，右端 100N 下压", backend="codex_strict")
    print(plan.model_dump_json(indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(cli_probe())
