"""The in-process registry of generated evidence artifacts.

An evidence artifact is written to a temp directory by one of the collectors
in this package and then has to stay reachable for the rest of the process's
life, because the page that triggered it renders download links. The registry
is that lookup: artifact id -> the files on disk plus the summary record the
UI lists.

It lived twice. `server.py` and `mcp_bridge.py` each carried their own copy --
203 lines, byte-identical except for three default `url_prefix` strings, one
serving `/api/evidence/...` and the other `/mcp/api/evidence/...`. Two copies
of a registry is two places to fix a leak and two chances for the record shape
the UI reads to drift apart.

The mount point is now a constructor argument and the state is instance
attributes, so the two callers stay independent the way they were: an artifact
generated through the bridge is not reachable through the server's URLs, and a
test clearing one does not clear the other.

Deliberately free of FastAPI. A missing artifact raises `ArtifactNotFound`
and the route decides that means 404 -- the registry does not know it is
behind HTTP.
"""

from __future__ import annotations

import json
import time
import uuid
import zipfile
from pathlib import Path
from typing import Any

from evidence.vault import create_vault_entry


class ArtifactNotFound(LookupError):
    """No such artifact id, or its file is gone from the temp directory."""


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _artifact_id(run_id: str) -> str:
    return f"{run_id}-{uuid.uuid4().hex[:8]}"


def _lookup(store: dict[str, dict[str, Any]], artifact_id: str,
            filename: str, what: str) -> Path:
    entry = store.get(artifact_id)
    files = entry.get("files", {}) if entry else {}
    if filename not in files:
        raise ArtifactNotFound("%s artifact not found" % what)
    path = files[filename]
    if not path.exists() or not path.is_file():
        raise ArtifactNotFound("%s artifact file missing" % what)
    return path


def _evidence_record(*, artifact_id: str, run_id: str, generated_at: str,
                     sequence: int, artifact_urls: dict[str, str],
                     evidence: dict[str, Any]) -> dict[str, Any]:
    contracts = evidence.get("contracts", {})
    diff = evidence.get("diff", {})
    capsule = evidence.get("capsule", {})
    return {
        "artifact_id": artifact_id,
        "run_id": run_id,
        "generated_at": generated_at,
        "sequence": sequence,
        "overall_status": evidence.get("overall_status"),
        "real_env_verified": evidence.get("real_env_verified"),
        "contracts": {
            "status": contracts.get("status"),
            "total": contracts.get("total"),
            "failed_count": contracts.get("failed_count"),
            "warning_count": contracts.get("warning_count"),
        },
        "diff": {
            "status": diff.get("status"),
            "total": diff.get("total"),
            "changed_count": diff.get("changed_count"),
            "added_count": diff.get("added_count"),
            "removed_count": diff.get("removed_count"),
        },
        "capsule": {
            "run_id": capsule.get("run_id"),
            "capsule_hash": capsule.get("capsule_hash"),
            "input_count": capsule.get("input_count"),
            "artifact_count": capsule.get("artifact_count"),
        },
        "artifact_urls": artifact_urls,
    }


def _write_bundle_zip(*, bundle_path: Path, artifact_id: str, run_id: str,
                      generated_at: str, evidence_path: Path, report_path: Path,
                      html_path: Path, capsule_manifest_path: Path) -> None:
    manifest = {
        "schema_version": "1.0",
        "artifact_id": artifact_id,
        "run_id": run_id,
        "generated_at": generated_at,
        "files": ["evidence.json", "evidence.md", "evidence.html", "capsule.json"],
    }
    with zipfile.ZipFile(bundle_path, "w", compression=zipfile.ZIP_DEFLATED) as bundle:
        bundle.write(evidence_path, "evidence.json")
        bundle.write(report_path, "evidence.md")
        bundle.write(html_path, "evidence.html")
        bundle.write(capsule_manifest_path, "capsule.json")
        bundle.writestr("bundle_manifest.json",
                        json.dumps(manifest, indent=2, sort_keys=True))


class EvidenceArtifactRegistry:
    """Artifacts generated by one process, and the URLs that process serves.

    `url_root` is the prefix everything hangs off -- "/api/evidence" for the
    workbench server, "/mcp/api/evidence" for the bridge. It is the only thing
    that differed between the two former copies.
    """

    def __init__(self, url_root: str) -> None:
        self.url_root = url_root.rstrip("/")
        self.artifacts: dict[str, dict[str, Any]] = {}
        self.demo_galleries: dict[str, dict[str, Any]] = {}
        self.sequence = 0

    def clear(self) -> None:
        self.artifacts.clear()
        self.demo_galleries.clear()
        self.sequence = 0

    # ── offline evidence ────────────────────────────────────────────

    def register_evidence(self, *, run_id: str, evidence: dict[str, Any],
                          evidence_path: Path, report_path: Path,
                          html_path: Path,
                          capsule_manifest_path: Path) -> dict[str, Any]:
        self.sequence += 1
        artifact_id = _artifact_id(run_id)
        generated_at = _now()
        bundle_path = report_path.parent / f"{artifact_id}.zip"
        _write_bundle_zip(
            bundle_path=bundle_path,
            artifact_id=artifact_id,
            run_id=run_id,
            generated_at=generated_at,
            evidence_path=evidence_path,
            report_path=report_path,
            html_path=html_path,
            capsule_manifest_path=capsule_manifest_path,
        )
        prefix = f"{self.url_root}/artifacts/{artifact_id}"
        artifact_urls = {
            "evidence_json": f"{prefix}/evidence.json",
            "report_markdown": f"{prefix}/evidence.md",
            "report_html": f"{prefix}/evidence.html",
            "capsule_manifest": f"{prefix}/capsule.json",
            "bundle_zip": f"{prefix}/bundle.zip",
        }
        self.artifacts[artifact_id] = {
            "files": {
                "evidence.json": evidence_path,
                "evidence.md": report_path,
                "evidence.html": html_path,
                "capsule.json": capsule_manifest_path,
                "bundle.zip": bundle_path,
            },
            "record": _evidence_record(
                artifact_id=artifact_id,
                run_id=run_id,
                generated_at=generated_at,
                sequence=self.sequence,
                artifact_urls=artifact_urls,
                evidence=evidence,
            ),
        }
        return {"artifact_id": artifact_id, "artifact_urls": artifact_urls}

    def evidence_files(self, artifact_id: str) -> dict[str, Path]:
        return self.artifacts[artifact_id]["files"]

    def evidence_path(self, artifact_id: str, filename: str) -> Path:
        return _lookup(self.artifacts, artifact_id, filename, "Evidence")

    def list_evidence_records(self, limit: int = 20) -> dict[str, Any]:
        safe_limit = max(1, min(limit, 100))
        items = [entry["record"] for entry in self.artifacts.values()
                 if "record" in entry]
        items.sort(key=lambda item: item["sequence"], reverse=True)
        return {"items": items[:safe_limit], "total": len(items)}

    # ── demo gallery ────────────────────────────────────────────────

    def register_demo_gallery(self, *, index: dict[str, Any],
                              out_dir: Path) -> dict[str, Any]:
        artifact_id = _artifact_id("demo-gallery")
        prefix = f"{self.url_root}/demo-gallery/{artifact_id}"
        artifact_urls = {
            "index_json": f"{prefix}/index.json",
            "index_markdown": f"{prefix}/index.md",
            "index_html": f"{prefix}/index.html",
            "gallery_zip": f"{prefix}/offline-demo-gallery.zip",
        }
        record = {
            "artifact_id": artifact_id,
            "generated_at": index["generated_at"],
            "overall_status": index["overall_status"],
            "case_count": index["case_count"],
            "cases": [
                {
                    "case": case["case"],
                    "overall_status": case["overall_status"],
                    "contracts_status": case["contracts_status"],
                    "diff_status": case["diff_status"],
                    "capsule_hash": case["capsule_hash"],
                }
                for case in index["cases"]
            ],
            "artifact_urls": artifact_urls,
        }
        self.demo_galleries[artifact_id] = {
            "files": {
                "index.json": out_dir / "index.json",
                "index.md": out_dir / "index.md",
                "index.html": out_dir / "index.html",
                "offline-demo-gallery.zip": Path(index["gallery_zip_path"]),
            },
            "record": record,
        }
        return {"artifact_id": artifact_id, "artifact_urls": artifact_urls,
                "record": record}

    def demo_gallery_path(self, artifact_id: str, filename: str) -> Path:
        return _lookup(self.demo_galleries, artifact_id, filename, "Demo gallery")

    # ── vault ───────────────────────────────────────────────────────

    def create_vault_entry(self, *, kind: str, title: str,
                           files: dict[str, Path],
                           summary: dict[str, Any]) -> dict[str, Any]:
        record = create_vault_entry(kind=kind, title=title, files=files,
                                    summary=summary)
        return {"vault_id": record["vault_id"],
                "vault_urls": self.vault_urls(record)}

    def vault_urls(self, record: dict[str, Any]) -> dict[str, str]:
        return {
            filename: f"{self.url_root}/vault/{record['vault_id']}/{filename}"
            for filename in record.get("files", {})
        }

    def attach_vault_urls(self, record: dict[str, Any]) -> None:
        record["vault_urls"] = self.vault_urls(record)
