#!/usr/bin/env python3
"""Real-solver check for reading a part out of a geometry file.

Until this, a part could only be built here, feature by feature. Every real
bracket, casting and housing arrives as a STEP or a SAT file, so the whole
dialect stopped at the boundary of what somebody was willing to re-draw.

The rig is a round trip, which is the only version of this test that can be
wrong in a way anybody would notice: one 10 x 10 x 100 bar, volume 10000.0 mm^3
exactly, is built in CAE, written out in each format, read back in through the
generator, and asked what it came to. A file fetched from somewhere else would
prove the reader works on that file; a round trip proves it against a number
this script computed itself.

  1. `import_step_round_trips_the_solid` -- and it must MESH and SOLVE, not
     merely report a volume. A part that imports and then meshes into nothing
     is the shape of failure this repository keeps finding.
  2. `import_acis_round_trips_the_solid` -- same bar, .sat.
  3. `import_iges_comes_back_hollow_and_is_refused` -- the counterexample, and
     the reason `expect.volume` or `expect.cells` is mandatory on an import.
     Measured: IGES returns 0 cells and volume 0.0 with NO exception, and the
     same 6 faces the solid has, so a face count cannot tell them apart.
  4. `import_a_missing_file_is_refused_before_abaqus_starts` -- a path that is
     not there costs a spec error, not a CAE start-up and a log to read.
  5. `import_the_stated_volume_is_checked_against_the_real_one` -- the import
     branch passing item 1 proves the check can say yes. This is the same
     import with a volume nobody's bar has, which must abort.

Exit codes: 0 = nothing failed (no Abaqus => "skipped", still 0);
            1 = at least one item ran and failed.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from core.helpers import check_abaqus  # noqa: E402
from runner import build_v2  # noqa: E402
from tools.abaqus_cmd import detect_abaqus_release, get_abaqus_cmd  # noqa: E402

MODEL = "GeometryImportCheck"
W = H = 10.0
L = 100.0
VOLUME = W * H * L                                       # 10000.0 mm^3
E, NU, RHO = 210000.0, 0.3, 7.85e-9
SEED = 5.0
# C3D8I, not C3D8R, and the difference is not a detail. Measured here on the
# imported bar, same file, same seed, one element code apart:
#
#   C3D8R seed 25   tip -17.237131   90.5x beam theory, job COMPLETED
#   C3D8I seed 25   tip  -0.185373    1.0x
#   C3D8R seed  5   tip  -0.253281    1.3x
#   C3D8I seed  5   tip  -0.189446    1.0x  (0.54% from P L^3 / 3EI)
#
# Reduced integration with one element through the thickness hourglasses, and
# nothing in the KPI path says so -- the job completes and returns a number
# ninety times too large. It cost this gate a red run to find, which is the
# whole argument for item 1 measuring a DISPLACEMENT and not just a volume: an
# import can deliver the exact right shape and still answer nonsense.
TIP_LOAD = 100.0
INERTIA = W * H ** 3 / 12.0
BEAM_TIP = TIP_LOAD * L ** 3 / (3.0 * E * INERTIA)       # 0.19047... mm

# The exporter for each format, and the opener that reads it back. Written out
# because the pairing is not derivable: writeAcisFile produces .sat, which
# openAcis reads, and neither name contains the other's.
FORMATS = (("step", "writeStepFile", "bar.step", "openStep", {}),
           ("acis", "writeAcisFile", "bar.sat", "openAcis", {}),
           ("iges", "writeIgesFile", "bar.igs", "openIges",
            {"flavor": "STANDARD"}))

_EXPORT_SCRIPT = '''# -*- coding: utf-8 -*-
"""Write one bar out in every format this gate reads back.

Not generated by runner/build_v2.py on purpose: the point of the round trip is
that the file came from somewhere the import path had no hand in.
"""
import json
import os

from abaqus import *
from abaqusConstants import *
import part

W, H, L = %(w)r, %(h)r, %(l)r
out = {}

m = mdb.Model(name='ExportSource')
s = m.ConstrainedSketch(name='prof', sheetSize=4.0 * L)
s.rectangle(point1=(0.0, 0.0), point2=(W, H))
p = m.Part(name='Bar', dimensionality=THREE_D, type=DEFORMABLE_BODY)
p.BaseSolidExtrude(sketch=s, depth=L)
out['source_volume'] = p.getVolume()
out['source_cells'] = len(p.cells)

for method, fname, extra in %(writers)s:
    kwargs = {'fileName': fname}
    for key, value in extra.items():
        kwargs[key] = globals()[value]
    try:
        getattr(p, method)(**kwargs)
        out[fname] = os.path.getsize(fname) if os.path.exists(fname) else 0
    except Exception, exc:
        out[fname] = 'ERR %%s: %%s' %% (type(exc).__name__, exc)

handle = open('exported.json', 'w')
handle.write(json.dumps(out))
handle.close()
'''


# --- plumbing --------------------------------------------------------------

def _export(work: Path) -> dict:
    """Build the bar in CAE and write it out in each format."""
    work.mkdir(parents=True, exist_ok=True)
    writers = [(method, fname, extra)
               for _tag, method, fname, _opener, extra in FORMATS]
    script = _EXPORT_SCRIPT % {
        "w": W, "h": H, "l": L,
        "writers": repr([(method, fname, dict((k, str(v))
                                              for k, v in extra.items()))
                         for method, fname, extra in writers]),
    }
    (work / "export_bar.py").write_text(script, encoding="utf-8")
    proc = subprocess.run(
        [get_abaqus_cmd(), "cae", "noGUI=export_bar.py"],
        cwd=str(work), stdin=subprocess.DEVNULL, capture_output=True,
        text=True, errors="replace", encoding="utf-8", timeout=1800)
    written = work / "exported.json"
    if not written.exists():
        return {"ok": False,
                "stderr": (proc.stderr or "")[-1500:]}
    out = json.loads(written.read_text(encoding="utf-8"))
    out["ok"] = True
    return out


def _spec(fmt: str, work: Path, expect=None, extra_open=None,
          file_name=None) -> dict:
    tag_to = dict((tag, (fname, opener))
                  for tag, _w, fname, opener, _e in FORMATS)
    fname, opener = tag_to[fmt]
    opener_call = {"call": opener,
                   "fileName": {"file": file_name or fname}}
    opener_call.update(extra_open or {})
    return {
        "meta": {"abaqus_release": "2021", "model_name": MODEL,
                 "units": "mm_MPa_t"},
        "material": {"name": "Steel", "E": E, "nu": NU, "density": RHO},
        "parts": [{
            "name": "Bar",
            "import": {"open": opener_call},
            "expect": expect if expect is not None
            else {"volume": VOLUME, "cells": 1},
            "section": {"type": "solid", "material": "Steel"},
            "mesh": {"seed": SEED, "element": "C3D8I",
                     "technique": "structured"},
        }],
        "assembly": {"instances": [{"name": "Imp", "part": "Bar",
                                    "translate": [0.0, 0.0, 0.0]}]},
        "steps": [{"call": "StaticStep", "name": {"literal": "One"},
                   "previous": {"literal": "Initial"}}],
        "conditions": [
            {"call": "EncastreBC", "name": {"literal": "Fix"},
             "createStepName": {"literal": "Initial"},
             "region": {"set": "Imp:face@z=min", "name": "FIX",
                        "expect": "=1"}},
            {"call": "SurfaceTraction", "name": {"literal": "Tip"},
             "createStepName": {"literal": "One"},
             "region": {"surface": "Imp:face@z=max", "name": "TIPFACE",
                        "expect": "=1"},
             "magnitude": TIP_LOAD / (W * H),
             "directionVector": [[0.0, 0.0, 0.0], [0.0, -1.0, 0.0]],
             "distributionType": "UNIFORM", "traction": "GENERAL"},
        ],
        "outputs": {"kpis": [{"name": "U_TIP", "type": "field_min",
                              "location": "whole_model", "component": "U2"}]},
    }


def _build(work: Path, spec: dict, spec_dir: Path) -> dict:
    work = work.resolve()
    work.mkdir(parents=True, exist_ok=True)
    for junk in ("selectors.log", "%s.inp" % MODEL):
        if (work / junk).exists():
            (work / junk).unlink()
    try:
        text = build_v2.generate_script(spec, spec_dir=spec_dir)
    except Exception as exc:
        return {"built": False, "log": "", "inp": "", "inp_written": False,
                "refused_at_generation": "%s: %s" % (type(exc).__name__, exc)}
    (work / "build_model_script.py").write_text(text, encoding="utf-8")
    proc = subprocess.run(
        [get_abaqus_cmd(), "cae", "noGUI=build_model_script.py", "--",
         str(work), "spec"],
        cwd=str(work), stdin=subprocess.DEVNULL, capture_output=True,
        text=True, errors="replace", encoding="utf-8", timeout=1800)
    log = work / "selectors.log"
    inp = work / ("%s.inp" % MODEL)
    return {"built": True,
            "log": log.read_text(encoding="utf-8", errors="replace")
                   if log.exists() else "",
            "inp": inp.read_text(encoding="utf-8", errors="replace")
                   if inp.exists() else "",
            "inp_written": inp.exists(),
            "stderr": (proc.stderr or "")[-2000:],
            "refused_at_generation": None}


def _solve(spec: dict, work: Path, spec_dir: Path) -> dict:
    """Run the whole pipeline, with the spec written next to the geometry.

    The orchestrator reads a spec from disk, and `{file:}` resolves against
    that file's directory -- so the spec has to live where the geometry is,
    which is also how a user would keep them.
    """
    import copy

    import yaml

    from agent.orchestrator import build_orchestrator

    work.mkdir(parents=True, exist_ok=True)
    spec_path = spec_dir / ("solve_%s.yaml" % work.name)
    spec_path.write_text(yaml.safe_dump(copy.deepcopy(spec), sort_keys=False,
                                        allow_unicode=True),
                         encoding="utf-8")
    return build_orchestrator(spec_path=spec_path, workdir=work,
                              expected_path=None, runner_cfg=None).run()


def _kpi(result: dict, name: str):
    value = (result.get("kpis") or {}).get(name)
    return value.get("value") if isinstance(value, dict) else value


def _line(out: dict, needle: str) -> str:
    for line in (out.get("log") or "").splitlines():
        if needle in line:
            return line.strip()
    return ""


def _skipped(item_id: str, reason: str) -> dict:
    return {"id": item_id, "status": "skipped", "reason": reason}


# --- items -----------------------------------------------------------------

def _round_trip(fmt: str, work: Path, geometry: Path) -> dict:
    """One format, imported and taken all the way to a displacement.

    The volume is the geometry arriving; the tip displacement is the geometry
    being USABLE. They are different claims: a part can report the right volume
    and still mesh into nothing, take an empty section, or lose the faces every
    selector here addresses.
    """
    result = _solve(_spec(fmt, work), work / "solve", geometry)
    tip = _kpi(result, "U_TIP")
    inp = work / "solve" / ("%s.inp" % MODEL)
    deck = inp.read_text(encoding="utf-8", errors="replace") if inp.exists() \
        else ""
    elements = len([ln for ln in deck.splitlines()
                    if ln.strip() and ln.strip()[0].isdigit()
                    and "," in ln]) if deck else 0

    problems = []
    if result.get("status") != "COMPLETED":
        problems.append("the job did not complete: %s / %s"
                        % (result.get("status"), str(result.get("error"))[:200]))
    if tip is None:
        problems.append("no U_TIP came back, so nothing measured the import")
    else:
        deviation = abs(tip - (-BEAM_TIP)) / BEAM_TIP
        if deviation > 0.05:
            problems.append(
                "tip %.7g against beam theory %.7g is %.2f%% out. A coarse "
                "mesh is expected to be stiff; this much says the geometry "
                "that arrived is not the bar that was exported."
                % (tip, -BEAM_TIP, deviation * 100.0))
    if "*Element" not in deck:
        problems.append(
            "the deck carries no *Element block, so the imported part meshed "
            "into nothing -- which a volume check alone would not have caught")

    return {
        "id": "import_%s_round_trips_the_solid" % fmt,
        "status": "pass" if not problems else "fail",
        "stated_volume": VOLUME,
        "measured_tip": tip,
        "beam_theory_tip": -BEAM_TIP,
        "deck_lines_with_numbers": elements,
        "note": "one bar written out of CAE in this format and read back "
                "through the import branch, then meshed, solved and compared "
                "with P L^3 / 3EI. The volume says the shape arrived; the "
                "displacement says it was usable.",
        "problems": problems,
    }


def check_step(work: Path, geometry: Path) -> dict:
    return _round_trip("step", work / "step", geometry)


def check_acis(work: Path, geometry: Path) -> dict:
    return _round_trip("acis", work / "acis", geometry)


def check_iges_is_hollow(work: Path, geometry: Path) -> dict:
    """The counterexample the whole `expect` rule rests on.

    Measured on Abaqus 2021 before this item was written: the same bar through
    IGES comes back with 0 cells and volume 0.0, raising nothing, and with the
    SAME 6 faces the solid has. So `expect: {faces: 6}` passes on a part that
    has no volume, takes an empty cell set, gets a section assignment over
    nothing, and meshes into nothing.

    Two builds. The first states the truth about the solid and must be refused
    at run time by the volume check. The second states only the face count --
    the spec somebody would write if the rule were "give it an expect block" --
    and must be refused at GENERATION time, before Abaqus starts.
    """
    stated = _build(work / "iges_volume", _spec("iges", work), geometry)
    faces_only = _build(work / "iges_faces", _spec("iges", work,
                                                   expect={"faces": 6}),
                        geometry)

    refusal = _line(stated, "EXPECT_VOLUME")
    problems = []
    if stated.get("inp_written"):
        problems.append(
            "the IGES build wrote an input file. It comes back with volume "
            "0.0 and no cells, so a deck from it is a part with no solid in "
            "it -- the check has to stop before the deck exists.")
    if not refusal:
        problems.append(
            "nothing in the log says why the IGES build stopped; the log "
            "ended with %r" % ((stated.get("log") or "").strip().splitlines()
                               or ["(empty)"])[-1])
    if faces_only.get("refused_at_generation") is None:
        problems.append(
            "`expect: {faces: 6}` on an import was not refused at generation "
            "time. Six faces is what BOTH the solid and the shell report, so "
            "that spec would have gone to Abaqus and passed.")
    elif "expect.volume" not in str(faces_only.get("refused_at_generation")):
        problems.append(
            "the refusal for a face-only expect does not name the keys that "
            "would work: %s"
            % str(faces_only.get("refused_at_generation"))[:200])

    return {
        "id": "import_iges_comes_back_hollow_and_is_refused",
        "status": "pass" if not problems else "fail",
        "refusal_line": refusal,
        "faces_only_refusal": str(
            faces_only.get("refused_at_generation") or "")[:300],
        "note": "IGES has no solid entity in the flavour Abaqus writes: the "
                "same bar returns 0 cells and volume 0.0 without raising, and "
                "6 faces either way. This is why an import must state volume "
                "or cells and why a face count is not accepted in their place.",
        "problems": problems,
    }


def check_missing_file(work: Path, geometry: Path) -> dict:
    """A path that is not there is a spec error, not a CAE start-up."""
    out = _build(work / "missing", _spec("step", work,
                                         file_name="not_here.step"), geometry)
    refusal = str(out.get("refused_at_generation") or "")
    problems = []
    if not refusal:
        problems.append("a missing geometry file was not refused at all")
    else:
        for wanted in ("does not exist", "no licence is taken"):
            if wanted not in refusal:
                problems.append("the refusal does not say %r: %s"
                                % (wanted, refusal[:200]))
    if out.get("built"):
        problems.append("Abaqus was launched for a file that is not there")
    return {
        "id": "import_a_missing_file_is_refused_before_abaqus_starts",
        "status": "pass" if not problems else "fail",
        "refusal": refusal[:300],
        "note": "the kernel does raise on a missing file, but it costs a CAE "
                "start-up and reports it in a log rather than against the "
                "spec line.",
        "problems": problems,
    }


def check_wrong_volume_aborts(work: Path, geometry: Path) -> dict:
    """The import check saying no.

    Item 1 shows it can say yes. Without this, a stated volume that is never
    compared would look exactly the same.
    """
    out = _build(work / "wrong_volume",
                 _spec("step", work, expect={"volume": VOLUME * 2.0,
                                             "cells": 1}), geometry)
    refusal = _line(out, "EXPECT_VOLUME")
    problems = []
    if out.get("inp_written"):
        problems.append(
            "a stated volume of %g on a part that measures %g wrote a deck"
            % (VOLUME * 2.0, VOLUME))
    if not refusal:
        problems.append("nothing in the log names the volume that did not match")
    return {
        "id": "import_the_stated_volume_is_checked_against_the_real_one",
        "status": "pass" if not problems else "fail",
        "stated_volume": VOLUME * 2.0,
        "true_volume": VOLUME,
        "refusal_line": refusal,
        "note": "the same import as item 1 with a volume nobody's bar has.",
        "problems": problems,
    }


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path,
                    default=ROOT / "artifacts" / "geometry_import_check"
                    / "report.json")
    ap.add_argument("--work", type=Path, default=None)
    args = ap.parse_args()

    work = args.work or (ROOT / "artifacts" / "geometry_import_check")
    work.mkdir(parents=True, exist_ok=True)
    started = time.time()

    names = ("import_step_round_trips_the_solid",
             "import_acis_round_trips_the_solid",
             "import_iges_comes_back_hollow_and_is_refused",
             "import_a_missing_file_is_refused_before_abaqus_starts",
             "import_the_stated_volume_is_checked_against_the_real_one")

    release = None
    if not check_abaqus():
        reason = ("Abaqus not found (set ABAQUS_AGENT_ABAQUS_CMD or put "
                  "abaqus.bat on PATH)")
        items = [_skipped(name, reason) for name in names]
    else:
        release = detect_abaqus_release()
        geometry = work / "exported"
        exported = _export(geometry)
        if not exported.get("ok"):
            reason = ("could not export the source bar: %s"
                      % str(exported.get("stderr"))[:300])
            items = [_skipped(name, reason) for name in names]
        else:
            items = [check_step(work, geometry),
                     check_acis(work, geometry),
                     check_iges_is_hollow(work, geometry),
                     check_missing_file(work, geometry),
                     check_wrong_volume_aborts(work, geometry)]

    failed = [i for i in items if i["status"] == "fail"]
    report = {
        "generated": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "abaqus_release": release,
        "seconds": round(time.time() - started, 1),
        "rig": {"volume": VOLUME, "beam_theory_tip": -BEAM_TIP,
                "tip_load_n": TIP_LOAD},
        "overall": "fail" if failed else "pass",
        "items": items,
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
