#!/usr/bin/env python3
"""Generate SteelFrameBlast.inp — a 3-story steel moment frame under air blast.

Structure (mm / MPa / t / s units, consistent with the rest of the repo):
  - 3 stories x 3.6 m, 3 bays x 6 m (X) by 2 bays x 6 m (Y)
  - Columns: welded I HW400x400x13x21, beams: HN500x200x10x16, all Q345
    bilinear plastic (fy 345 MPa, Et 2 GPa)
  - Floors: 120 mm C30 concrete slabs (S4R), sharing nodes with the beam
    grid (rigid connection, composite action ignored)
  - Mesh: 600 mm for beams, columns and slabs

Blast (same Kingery-Bulmash / Friedlander fits as runner/build_model.py):
  - 200 kg TNT at 12 m in front of the front face (y = -12 m), 1 m height
  - Each front column line gets its own reflected overpressure P(t):
    peak and duration from its own standoff, arrival delayed by distance
    (traveling wave across the facade, shock speed ~450 m/s near field)
  - Cladding is not modeled: each front column carries its tributary width
    (6 m interior / 3 m corner) as nodal forces in +Y

The output INP runs through the normal agent pipeline via geometry type
custom_inp. Deterministic: same inputs -> byte-identical INP.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent

# ── Structure ─────────────────────────────────────────────────────────────
BAY = 6000.0          # mm
STORY = 3600.0        # mm
N_BAY_X = 3
N_BAY_Y = 2
N_STORY = 3
MESH = 600.0          # mm element length everywhere

NX = int(N_BAY_X * BAY / MESH)      # 30 slab divisions in X
NY = int(N_BAY_Y * BAY / MESH)      # 20 in Y
NZ = int(N_STORY * STORY / MESH)    # 18 column divisions
COL_I = [int(c * BAY / MESH) for c in range(N_BAY_X + 1)]   # 0,10,20,30
COL_J = [int(c * BAY / MESH) for c in range(N_BAY_Y + 1)]   # 0,10,20
FLOOR_M = [int((s + 1) * STORY / MESH) for s in range(N_STORY)]  # 6,12,18

# ── Blast scenario ────────────────────────────────────────────────────────
TNT_KG = 200.0
STANDOFF_MM = 12000.0        # from front face (y=0) to charge
CHARGE_X_MM = (N_BAY_X * BAY) / 2.0   # in front of facade center
CHARGE_Z_MM = 1000.0
SHOCK_SPEED_MM_S = 450.0e3   # ~450 m/s average near-field front speed
TIME_PERIOD = 0.2            # s
FIELD_INTERVALS = 150
WAVE_DECAY_B = 1.0
N_AMP_PTS = 30


def nid(i: int, j: int, m: int) -> int:
    return 1 + m * 100000 + j * 1000 + i


def kingery_bulmash(tnt_kg: float, r_m: float) -> tuple[float, float]:
    """Reflected peak overpressure (MPa) and positive phase duration (s).

    Same simplified Mills / Kinney-Graham fits as runner/build_model.py.
    """
    z = r_m / (tnt_kg ** (1.0 / 3.0))
    z = min(max(z, 0.05), 40.0)
    p_kpa = 1772.0 / z**3 - 114.0 / z**2 + 108.0 / z
    p_ref_kpa = p_kpa * (2.0 + 6.0 * math.exp(-0.5 * z))
    p_max_mpa = max(p_ref_kpa / 1000.0, 0.001)
    td_ms = (
        980.0 * (1 + (z / 0.54) ** 10)
        / ((1 + (z / 0.02) ** 3) * (1 + (z / 0.74) ** 6) * math.sqrt(1 + (z / 6.9) ** 2))
        * (tnt_kg ** (1.0 / 3.0))
    )
    td_s = min(max(td_ms / 1000.0, 1e-5), TIME_PERIOD * 0.5)
    return p_max_mpa, td_s


def friedlander_points(td_s: float, t_arrive: float) -> list[tuple[float, float]]:
    rise = 1e-4  # near-instant shock front, kept finite for a monotonic table
    pts = [(0.0, 0.0), (t_arrive, 0.0)]
    for k in range(N_AMP_PTS + 1):
        ti = td_s * k / N_AMP_PTS
        amp = 0.0 if ti >= td_s else (1.0 - ti / td_s) * math.exp(-WAVE_DECAY_B * ti / td_s)
        pts.append((t_arrive + rise + ti, amp))
    pts.append((TIME_PERIOD, 0.0))
    return pts


def build() -> tuple[str, dict]:
    lines: list[str] = []
    w = lines.append

    w("*HEADING")
    w("SteelFrameBlast: %d-story Q345 moment frame, %.0fkg TNT @ %.0fm front standoff"
      % (N_STORY, TNT_KG, STANDOFF_MM / 1000.0))
    w("** Generated by cases/steel_frame_blast/generate_inp.py — do not edit by hand")
    w("** Units: mm, MPa, tonne, s")

    # ── Nodes ──
    w("*NODE, NSET=ALLNODES")
    floor_set = set(FLOOR_M)
    for m in range(NZ + 1):
        z = m * MESH
        if m in floor_set:
            for j in range(NY + 1):
                for i in range(NX + 1):
                    w("%d, %.1f, %.1f, %.1f" % (nid(i, j, m), i * MESH, j * MESH, z))
        else:
            for j in COL_J:
                for i in COL_I:
                    w("%d, %.1f, %.1f, %.1f" % (nid(i, j, m), i * MESH, j * MESH, z))

    # ── Column elements ──
    w("*ELEMENT, TYPE=B31, ELSET=COLUMNS")
    eid = 1000000
    for j in COL_J:
        for i in COL_I:
            for m in range(NZ):
                eid += 1
                w("%d, %d, %d" % (eid, nid(i, j, m), nid(i, j, m + 1)))

    # ── X-direction beams at each floor ──
    w("*ELEMENT, TYPE=B31, ELSET=XBEAMS")
    eid = 2000000
    for m in FLOOR_M:
        for j in COL_J:
            for i in range(NX):
                eid += 1
                w("%d, %d, %d" % (eid, nid(i, j, m), nid(i + 1, j, m)))

    # ── Y-direction beams at each floor ──
    w("*ELEMENT, TYPE=B31, ELSET=YBEAMS")
    eid = 3000000
    for m in FLOOR_M:
        for i in COL_I:
            for j in range(NY):
                eid += 1
                w("%d, %d, %d" % (eid, nid(i, j, m), nid(i, j + 1, m)))

    # ── Slab shells at each floor ──
    w("*ELEMENT, TYPE=S4R, ELSET=SLABS")
    eid = 4000000
    for m in FLOOR_M:
        for j in range(NY):
            for i in range(NX):
                eid += 1
                w("%d, %d, %d, %d, %d" % (
                    eid, nid(i, j, m), nid(i + 1, j, m), nid(i + 1, j + 1, m), nid(i, j + 1, m)))

    # ── Node sets ──
    w("*NSET, NSET=BASE")
    w(", ".join(str(nid(i, j, 0)) for j in COL_J for i in COL_I))
    w("*NSET, NSET=ROOF_CENTER")
    w(str(nid(NX // 2, NY // 2, FLOOR_M[-1])))

    for idx, i in enumerate(COL_I):
        nodes_mid = [nid(i, 0, m) for m in range(1, NZ)]
        nodes_end = [nid(i, 0, 0), nid(i, 0, NZ)]
        w("*NSET, NSET=FRONT_C%d_MID" % idx)
        for start in range(0, len(nodes_mid), 12):
            w(", ".join(str(n) for n in nodes_mid[start:start + 12]))
        w("*NSET, NSET=FRONT_C%d_END" % idx)
        w(", ".join(str(n) for n in nodes_end))

    # ── Materials ──
    w("*MATERIAL, NAME=STEEL_Q345")
    w("*ELASTIC")
    w("210000.0, 0.3")
    w("*PLASTIC")
    w("345.0, 0.0")
    w("745.0, 0.2")
    w("*DENSITY")
    w("7.85e-09,")
    w("*MATERIAL, NAME=CONCRETE_C30")
    w("*ELASTIC")
    w("30000.0, 0.2")
    w("*DENSITY")
    w("2.5e-09,")

    # ── Sections (I profiles; local 1-2 axes set per member direction) ──
    w("*BEAM SECTION, ELSET=COLUMNS, MATERIAL=STEEL_Q345, SECTION=I")
    w("200.0, 400.0, 400.0, 400.0, 21.0, 21.0, 13.0")
    w("1.0, 0.0, 0.0")
    w("*BEAM SECTION, ELSET=XBEAMS, MATERIAL=STEEL_Q345, SECTION=I")
    w("250.0, 500.0, 200.0, 200.0, 16.0, 16.0, 10.0")
    w("0.0, 1.0, 0.0")
    w("*BEAM SECTION, ELSET=YBEAMS, MATERIAL=STEEL_Q345, SECTION=I")
    w("250.0, 500.0, 200.0, 200.0, 16.0, 16.0, 10.0")
    w("-1.0, 0.0, 0.0")
    w("*SHELL SECTION, ELSET=SLABS, MATERIAL=CONCRETE_C30")
    w("120.0,")

    # ── Boundary ──
    w("*BOUNDARY")
    w("BASE, ENCASTRE")

    # ── Blast amplitudes + loads per front column line ──
    manifest_lines = []
    r_list = []
    for idx, i in enumerate(COL_I):
        dx_m = (i * MESH - CHARGE_X_MM) / 1000.0
        r_m = math.sqrt(dx_m**2 + (STANDOFF_MM / 1000.0) ** 2)
        r_list.append(r_m)
    r_min = min(r_list)

    cload_lines: list[str] = []
    for idx, i in enumerate(COL_I):
        r_m = r_list[idx]
        p_max, td_s = kingery_bulmash(TNT_KG, r_m)
        # 0.5 ms lead-in keeps every amplitude table strictly increasing
        t_arrive = 5e-4 + (r_m - r_min) * 1000.0 / SHOCK_SPEED_MM_S
        w("*AMPLITUDE, NAME=BLAST_C%d, DEFINITION=TABULAR" % idx)
        pts = friedlander_points(td_s, t_arrive)
        for start in range(0, len(pts), 4):
            w(", ".join("%.6e, %.6e" % (t, a) for t, a in pts[start:start + 4]))

        trib_w = BAY if 0 < i < NX else BAY / 2.0     # corner columns carry half
        f_mid = p_max * trib_w * MESH                 # N at full amplitude
        f_end = f_mid / 2.0
        cload_lines.append("*CLOAD, AMPLITUDE=BLAST_C%d" % idx)
        cload_lines.append("FRONT_C%d_MID, 2, %.6e" % (idx, f_mid))
        cload_lines.append("FRONT_C%d_END, 2, %.6e" % (idx, f_end))
        manifest_lines.append({
            "column_x_mm": i * MESH,
            "standoff_m": round(r_m, 3),
            "scaled_distance": round(r_m / TNT_KG ** (1.0 / 3.0), 3),
            "p_reflected_mpa": round(p_max, 4),
            "td_ms": round(td_s * 1000.0, 3),
            "arrival_ms": round(t_arrive * 1000.0, 3),
            "node_force_peak_n": round(f_mid, 1),
        })

    # ── Step ──
    w("*STEP, NAME=Blast")
    w("*DYNAMIC, EXPLICIT")
    w(", %.6f" % TIME_PERIOD)
    for line in cload_lines:
        w(line)
    w("*OUTPUT, FIELD, NUMBER INTERVAL=%d" % FIELD_INTERVALS)
    w("*ELEMENT OUTPUT, ELSET=COLUMNS")
    w("S, PEEQ")
    w("*ELEMENT OUTPUT, ELSET=XBEAMS")
    w("S, PEEQ")
    w("*ELEMENT OUTPUT, ELSET=YBEAMS")
    w("S, PEEQ")
    w("*ELEMENT OUTPUT, ELSET=SLABS")
    w("S,")
    w("*NODE OUTPUT")
    w("U, V")
    w("*OUTPUT, HISTORY, FREQUENCY=10")
    w("*ENERGY OUTPUT")
    w("ALLKE, ALLIE, ALLPD, ALLSE, ETOTAL")
    w("*NODE OUTPUT, NSET=ROOF_CENTER")
    w("U2, V2")
    w("*END STEP")

    manifest = {
        "tnt_kg": TNT_KG,
        "standoff_mm": STANDOFF_MM,
        "charge_position_mm": [CHARGE_X_MM, -STANDOFF_MM, CHARGE_Z_MM],
        "stories": N_STORY,
        "bays": [N_BAY_X, N_BAY_Y],
        "mesh_mm": MESH,
        "time_period_s": TIME_PERIOD,
        "field_intervals": FIELD_INTERVALS,
        "front_columns": manifest_lines,
        "assumptions": [
            "cladding not modeled: front columns take tributary facade pressure",
            "gravity not applied (blast response only)",
            "slab composite action ignored (shared nodes = rigid connection)",
            "concrete slab elastic; plasticity concentrated in steel frame",
        ],
    }
    return "\n".join(lines) + "\n", manifest


def main() -> int:
    inp_text, manifest = build()
    inp_path = HERE / "SteelFrameBlast.inp"
    inp_path.write_text(inp_text, encoding="utf-8")
    (HERE / "blast_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    n_nodes = inp_text.count("\n*NODE") and sum(
        1 for ln in inp_text.splitlines() if ln and ln[0].isdigit() and "," in ln
    )
    print("wrote %s (%.0f KB, ~%d data lines)" % (inp_path, inp_path.stat().st_size / 1024, n_nodes))
    print(json.dumps(manifest["front_columns"], indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
