"""
ccx_mesh.py
-----------
Pure-Python structured mesher for the CalculiX fallback backend.

Why this exists: every mesh in this repo is generated by ``abaqus cae noGUI``
(runner/build_model.py:803). On a machine WITHOUT Abaqus there is therefore no
way to produce a deck at all — the fallback would be stuck before it started.
This module meshes the one geometry the fallback supports, in plain Python,
with no solver of any kind.

Scope is deliberately one geometry (``cantilever_block``). Anything else raises,
so the capability table in ``core/backends.py`` and the generator can never
drift apart: if it is not meshed here it is refused there.

Discretisation matches what CAE produces for the same spec — seed 5.0 on
100x10x10 gives 20x2x2 = 80 C3D20R elements / 621 nodes, the same counts as the
frozen Abaqus run cases/cantilever/runs/dd6ec1145b8de62f. Node NUMBERING is our
own, so every KPI must resolve through a named set, never a hard-coded node id.
"""

from __future__ import annotations

from dataclasses import dataclass

# Abaqus/CalculiX C3D20 local node order, expressed as (dx, dy, dz) offsets in
# half-cell grid steps from the cell origin. 1-4 bottom corners, 5-8 top
# corners, 9-12 bottom mid-edges, 13-16 top mid-edges, 17-20 vertical mid-edges.
_C3D20_OFFSETS = (
    (0, 0, 0), (2, 0, 0), (2, 2, 0), (0, 2, 0),
    (0, 0, 2), (2, 0, 2), (2, 2, 2), (0, 2, 2),
    (1, 0, 0), (2, 1, 0), (1, 2, 0), (0, 1, 0),
    (1, 0, 2), (2, 1, 2), (1, 2, 2), (0, 1, 2),
    (0, 0, 1), (2, 0, 1), (2, 2, 1), (0, 2, 1),
)


@dataclass(frozen=True)
class StructuredMesh:
    """A finished mesh plus the named sets the KPI layer resolves against."""

    element_type: str
    nodes: tuple[tuple[int, float, float, float], ...]
    elements: tuple[tuple[int, tuple[int, ...]], ...]
    node_sets: dict[str, tuple[int, ...]]
    element_sets: dict[str, tuple[int, ...]]

    @property
    def node_count(self) -> int:
        return len(self.nodes)

    @property
    def element_count(self) -> int:
        return len(self.elements)


def _divisions(length: float, seed: float) -> int:
    """Number of elements along an edge, matching CAE's seeding behaviour."""
    if seed <= 0:
        raise ValueError("seed_size must be > 0")
    return max(1, int(round(length / seed)))


def cantilever_block_mesh(geo: dict) -> StructuredMesh:
    """Mesh a cantilever block with quadratic reduced-integration hexes.

    Axis convention is the one runner/build_model.py:391-404 builds in CAE:
    x in [0, W], y in [0, H], z in [0, L], fixed face at z=0, loaded face at
    z=L, tip node nearest (W/2, H/2) on the loaded face.
    """
    length = float(geo["L"])
    width = float(geo["W"])
    height = float(geo["H"])
    seed = float(geo.get("seed_size") or min(length, width, height) / 4.0)

    n_x = _divisions(width, seed)
    n_y = _divisions(height, seed)
    n_z = _divisions(length, seed)

    # Serendipity grid: half-steps in every direction; a grid point carries a
    # node only when at most one index is odd (no face-centre / body-centre
    # nodes in a 20-node brick).
    step_x = width / (2.0 * n_x)
    step_y = height / (2.0 * n_y)
    step_z = length / (2.0 * n_z)

    node_ids: dict[tuple[int, int, int], int] = {}
    nodes: list[tuple[int, float, float, float]] = []
    next_id = 1
    for i_z in range(2 * n_z + 1):
        for i_y in range(2 * n_y + 1):
            for i_x in range(2 * n_x + 1):
                if (i_x % 2) + (i_y % 2) + (i_z % 2) > 1:
                    continue
                node_ids[(i_x, i_y, i_z)] = next_id
                nodes.append((next_id, i_x * step_x, i_y * step_y, i_z * step_z))
                next_id += 1

    elements: list[tuple[int, tuple[int, ...]]] = []
    fixed_elements: list[int] = []
    load_elements: list[int] = []
    elem_id = 1
    for c_z in range(n_z):
        for c_y in range(n_y):
            for c_x in range(n_x):
                base = (2 * c_x, 2 * c_y, 2 * c_z)
                conn = tuple(
                    node_ids[(base[0] + d_x, base[1] + d_y, base[2] + d_z)]
                    for d_x, d_y, d_z in _C3D20_OFFSETS
                )
                elements.append((elem_id, conn))
                if c_z == 0:
                    fixed_elements.append(elem_id)
                if c_z == n_z - 1:
                    load_elements.append(elem_id)
                elem_id += 1

    fixed_nodes = tuple(
        nid for (_i_x, _i_y, i_z), nid in sorted(node_ids.items(), key=lambda kv: kv[1])
        if i_z == 0
    )
    load_nodes = tuple(
        nid for (_i_x, _i_y, i_z), nid in sorted(node_ids.items(), key=lambda kv: kv[1])
        if i_z == 2 * n_z
    )
    tip_node = _tip_node(node_ids, n_x, n_y, n_z, step_x, step_y, width, height)

    all_nodes = tuple(n[0] for n in nodes)
    all_elements = tuple(e[0] for e in elements)

    return StructuredMesh(
        element_type="C3D20R",
        nodes=tuple(nodes),
        elements=tuple(elements),
        node_sets={
            "ALL": all_nodes,
            "FIXED_END": fixed_nodes,
            "LOAD_END": load_nodes,
            "TIP_NODES": (tip_node,),
        },
        element_sets={
            "ALL": all_elements,
            "FIXED_END": tuple(fixed_elements),
            "LOAD_END": tuple(load_elements),
        },
    )


def _tip_node(
    node_ids: dict[tuple[int, int, int], int],
    n_x: int, n_y: int, n_z: int,
    step_x: float, step_y: float,
    width: float, height: float,
) -> int:
    """Node on the loaded face closest to its centre (same rule as CAE)."""
    target_x, target_y = width / 2.0, height / 2.0
    best_id, best_dist = None, None
    for (i_x, i_y, i_z), nid in node_ids.items():
        if i_z != 2 * n_z:
            continue
        dist = (i_x * step_x - target_x) ** 2 + (i_y * step_y - target_y) ** 2
        if best_dist is None or dist < best_dist - 1e-12:
            best_dist, best_id = dist, nid
    if best_id is None:  # pragma: no cover - grid always has a loaded face
        raise ValueError("no node found on the loaded face")
    return best_id


def build_mesh(spec: dict) -> StructuredMesh:
    """Dispatch on geometry.type. Unknown geometry is a hard error, not a guess."""
    geo = spec.get("geometry", {}) or {}
    geo_type = geo.get("type")
    if geo_type == "cantilever_block":
        return cantilever_block_mesh(geo)
    raise ValueError(
        "CalculiX 后端没有 %r 的网格生成器（只支持 cantilever_block）" % (geo_type,)
    )
