"""The Python 2.7 the Abaqus kernel runs, as text.

runner/build_v2.py is Python 3 host code that EMITS Python 2.7: the CAE kernel
on this machine reports 2.7.15, and Abaqus only moved to 3.10.5 at the 2024
release. So nothing inside these strings may use an f-string, a type
annotation, or pathlib.

They lived inside build_v2.py as two constants totalling 1777 of that file's
6021 lines -- 29% of a module whose actual job is compiling a spec, spent on a
payload that never varies and that no reader scrolling for the compiler wants
to page through.

HELPERS is split into topical chunks for navigation ONLY. `HELPERS`
concatenates them in order, and tests/test_kernel_runtime.py pins that
concatenation against the five shipped decks, so the split cannot quietly
become a rewrite.
"""

from __future__ import annotations

_PREAMBLE = """# -*- coding: utf-8 -*-
# AUTO-GENERATED by abaqus-agent runner/build_v2.py (spec v2 assembly dialect)
# DO NOT EDIT - regenerate from spec.yaml
# RUN: abaqus cae noGUI=build_model_script.py -- <workdir> <spec_path>

import sys
import os

workdir = sys.argv[-2] if len(sys.argv) >= 3 else os.getcwd()
os.chdir(workdir)

from abaqus import *
from abaqusConstants import *
%s

%s

MODEL = %r
if MODEL not in mdb.models.keys():
    mdb.Model(name=MODEL)
m = mdb.models[MODEL]
"""

# Kept out of the %-formatted preamble on purpose: this text is full of %s
# format strings of its own, and one stray % here used to be a TypeError at
# generation time rather than anything a reader could see.

# interactions -- tie and surface-to-surface contact
_H_INTERACTIONS = '''

# The generator's CENTROID_TOL_FLOOR / CENTROID_TOL_FACTOR, restated here
# because this preamble is a literal and cannot interpolate them. The two pairs
# are pinned equal by tests/test_build_v2_generic.py, so editing one and not the
# other fails the suite rather than silently loosening a check on the machine.
_CENTROID_TOL_FLOOR = 1.0e-3
_CENTROID_TOL_FACTOR = 2.0e-3


# Tie a pair using whichever keyword names this release accepts. Abaqus renamed
# master/slave to main/secondary, but not everywhere at once: measured on
# Abaqus 2021, Constraint.Tie still wants master=/slave= and answers main= with
# "TypeError: keyword error on main". Trying the new names first means a deck
# written here keeps working after an upgrade, which is not hypothetical - a
# 2024 install is planned on this machine.
def _tie(model, name, main_surface, secondary_surface, **kwargs):
    try:
        return model.Tie(name=name, main=main_surface,
                         secondary=secondary_surface, **kwargs)
    except TypeError:
        return model.Tie(name=name, master=main_surface,
                         slave=secondary_surface, **kwargs)


# Same story for surface-to-surface contact: the keyword rename did not land
# everywhere in the same release, so try the new names and fall back.
def _contact(model, name, main_surface, secondary_surface, **kwargs):
    try:
        return model.SurfaceToSurfaceContactStd(
            name=name, main=main_surface, secondary=secondary_surface, **kwargs)
    except TypeError:
        return model.SurfaceToSurfaceContactStd(
            name=name, master=main_surface, slave=secondary_surface, **kwargs)


# Profiles recorded by the sketch features, so a cut can redraw them against a
# sketch transform. See _cut below for why redrawing is necessary.
#
# Keyed by (part, sketch id), not by id alone. Sketch ids are only unique WITHIN
# a part, and two parts each with a sketch called 'hole' would share one entry.
# Emission order happens to make that harmless today -- each part's lines run
# contiguously, so the entry is always the right one when it is read -- but that
# is an accident of layout, and the day a feature is emitted out of order it
# would cut the wrong circle without a word.
_SKETCHES = {}

# Results bound by a feature's `as:`, so a later feature can refer to them. A
# datum plane is the case that forces this to exist: DatumPlaneByPrincipalPlane
# returns a FEATURE, the datum itself lives at part.datums[feature.id], and
# MakeSketchTransform wants the datum. There is no way to write that as a
# literal.
_RESULTS = {}


'''

# dispatch -- the generic new/call shim and its sequence test
_H_DISPATCH = '''\
def _is_geom_sequence(value):
    """Is this one of Abaqus's own geometry sequences (rather than a tuple)?

    Used only to decide whether a TypeError is worth retrying. Deliberately
    structural: there is no base class to test against that is stable across
    faces / edges / cells / vertices sequences.
    """
    if isinstance(value, (tuple, list, int, float)):
        return False
    try:
        if isinstance(value, basestring):
            return False
    except NameError:
        if isinstance(value, str):
            return False
    return hasattr(value, '__len__') and hasattr(value, '__getitem__')


def _gnew(module_name, class_name, kwargs, label):
    \"\"\"Construct an Abaqus object that a keyword needs, rather than call a method.

    mesh.ElemType is why this exists: setElementType(elemTypes=(...)) wants
    built objects, and ElemType lives in a module, not on the part. Everything
    else about it matches _gcall -- unknown module, unknown class and bad
    keywords are all loud.
    \"\"\"
    module = _MODULES.get(module_name)
    if module is None:
        raise ValueError('GENERIC_NO_MODULE: %s asked for %r; the script '
                         'imports %s.' % (label, module_name,
                                          ', '.join(sorted(_MODULES))))
    if class_name.startswith('_'):
        raise ValueError('GENERIC_REFUSED: %s asked for %r, which is not a '
                         'public name.' % (label, class_name))
    try:
        factory = getattr(module, class_name)
    except Exception:
        raise ValueError('GENERIC_NO_CLASS: %s asked for %s.%s, which does not '
                         'exist.' % (label, module_name, class_name))
    return factory(**kwargs)


# Measured on Abaqus 2021: setElementType with C3D8R + C3D6 + C3D10 raises
# "Default args are not fully supported", which mentions neither the argument
# nor the reason. The same call with C3D8R/C3D6/C3D4 (all linear) and with
# C3D20R/C3D15/C3D10 (all quadratic) both succeed, so the trigger is a mixed
# element ORDER in the hex/wedge/tet triple. The message is useless on its own,
# so the observation is attached to it rather than left for the next person to
# rediscover.
# Abaqus renamed master/slave to main/secondary, and did not finish: measured on
# Abaqus 2021, Tie and SurfaceToSurfaceContactStd still answer main= with
# "TypeError: keyword error on main", while newer releases refuse master=. A
# deck should not have to know which install it will meet, and the mismatch is a
# TypeError naming the exact keyword, so renaming and trying once more is as
# safe as the tuple retry below it. Both directions, so decks travel both ways.
_PAIR_RENAMES = (('main', 'master'), ('master', 'main'),
                 ('secondary', 'slave'), ('slave', 'secondary'))
_PAIR_RENAME_MAP = {'main': {'main': 'master', 'secondary': 'slave'},
                    'master': {'master': 'main', 'slave': 'secondary'},
                    'secondary': {'main': 'master', 'secondary': 'slave'},
                    'slave': {'master': 'main', 'slave': 'secondary'}}

_ORDER_HINT = ('Default args are not fully supported',
               ' -- measured on Abaqus 2021, this appears when the element '
               'types passed to setElementType mix orders: C3D8R (linear hex) '
               'with C3D10 (quadratic tet) fails, while all-linear '
               '(C3D8R/C3D6/C3D4) and all-quadratic (C3D20R/C3D15/C3D10) both '
               'work.')


def _gcall(obj, name, kwargs, label):
    \"\"\"Call an Abaqus method named by the spec.

    Measured on Abaqus 2021, every way of getting this wrong is loud, which is
    the whole reason it is safe to offer:

      * a method that does not exist  -> AttributeError naming it
      * a keyword that does not exist -> "TypeError: keyword error on pointTwo"
      * a wrong argument type         -> "TypeError: point1; found string,
                                          expecting tuple"

    The one retry below is not a guess either. Round(edgeList=) and
    Chamfer(edgeList=) refuse a GeomSequence with "found GeomSequence, expecting
    tuple", while Set(edges=) requires the GeomSequence and refuses a tuple. The
    shape a geometry argument must take is therefore per-method, with no rule
    behind it -- but the mismatch is a TypeError that names the argument, so
    converting and trying once more is safe. A TypeError with no geometry
    sequence in the call is re-raised untouched; so is a second failure.
    \"\"\"
    if name.startswith('_'):
        _expect_fail('GENERIC_REFUSED: %s asked for %r, which is not a public '
                     'API name.' % (label, name))
    try:
        method = getattr(obj, name)
    except Exception:
        _expect_fail('GENERIC_NO_METHOD: %s asked for %r, which %s does not '
                     'have.' % (label, name, type(obj).__name__))
    before = _registry_sizes(obj) if 'name' in kwargs else None
    try:
        try:
            result = method(**kwargs)
        except TypeError:
            detail = str(sys.exc_info()[1])
            for old, new in _PAIR_RENAMES:
                if 'keyword error on ' + old not in detail or old not in kwargs:
                    continue
                renamed = {}
                for key in kwargs:
                    renamed[_PAIR_RENAME_MAP[old].get(key, key)] = kwargs[key]
                result = method(**renamed)
                _sel_log('GENERIC_RENAMED: %s %s -- this release wants %s, '
                         'not %s' % (label, name, new, old))
                return result
            retried = {}
            converted = []
            for key in kwargs:
                value = kwargs[key]
                if _is_geom_sequence(value):
                    retried[key] = tuple(value)
                    converted.append(key)
                else:
                    retried[key] = value
            if not converted:
                raise
            result = method(**retried)
            _sel_log('GENERIC_RETRIED: %s %s -- passed %s as tuple(s)'
                     % (label, name, ', '.join(converted)))
            return result
    except Exception:
        detail = str(sys.exc_info()[1])
        if _ORDER_HINT[0] in detail:
            _expect_fail('GENERIC_FAILED: %s %s -> %s%s'
                         % (label, name, detail, _ORDER_HINT[1]))
        # Logged and then re-raised untouched: the exception is Abaqus's own and
        # says more than a rewording would, but print() from a noGUI script does
        # not reach the launcher, so without this line the log just stops.
        _sel_log('GENERIC_FAILED: %s %s -> %s' % (label, name, detail))
        raise
    if before is not None:
        _expect_created(obj, before, kwargs['name'], label, name)
    _sel_log('GENERIC_OK: %s %s' % (label, name))
    return result


_REGISTRY_NAMES = {}


'''

# creation -- did the call create what it said it created
_H_CREATION = '''\
def _registry_names(obj):
    \"\"\"The repository attributes this object carries, found rather than listed.

    A written-out list would be a second enumeration to keep in step with the
    release, which is the thing this whole layer exists to avoid. Cached per
    type because dir() on a Model is three hundred attributes and this runs once
    per named call.
    \"\"\"
    key = type(obj).__name__
    if key in _REGISTRY_NAMES:
        return _REGISTRY_NAMES[key]
    found = []
    for attr in dir(obj):
        if attr.startswith('_'):
            continue
        try:
            value = getattr(obj, attr)
        except Exception:
            continue
        if callable(value):
            continue
        if hasattr(value, 'keys'):
            found.append(attr)
    _REGISTRY_NAMES[key] = tuple(found)
    return _REGISTRY_NAMES[key]


def _registry_sizes(obj):
    sizes = {}
    for attr in _registry_names(obj):
        try:
            sizes[attr] = len(getattr(obj, attr).keys())
        except Exception:
            continue
    return sizes


def _expect_created(obj, before, wanted, label, call):
    \"\"\"A named call must have ADDED something, not replaced something.

    Measured on Abaqus 2021: a second DisplacementBC of a name that already
    exists does not raise and does not add -- it replaces the first, keeping
    only the later region and the later step, so the earlier step silently ends
    up with no boundary card at all. The job then completes and answers a
    question nobody asked.

    Nothing here knows which registry a given call writes into, and it does not
    need to: if no registry grew and the name is sitting in one afterwards, the
    call landed on top of something. A call that creates nothing and is not in
    any registry (a query, a setter) is left alone.
    \"\"\"
    after = _registry_sizes(obj)
    for attr in after:
        if after[attr] > before.get(attr, 0):
            return
    name = str(wanted)
    for attr in _registry_names(obj):
        try:
            keys = getattr(obj, attr).keys()
        except Exception:
            continue
        if name in keys:
            _expect_fail(
                'NAME_REPLACED: %s called %s(name=%r) and nothing new appeared '
                '-- %s already held that name, so this REPLACED it rather than '
                'adding to it. Abaqus does not warn: the earlier one keeps only '
                'the later region and the later step, and the step it used to '
                'act in ends up empty. Give the second one a name of its own; '
                'if it is meant to be the same condition with a new value, '
                'that is setValuesInStep on the condition itself -- bind the '
                'first with as: and call into it with target: {ref: ...}.'
                % (label, call, name, attr))


def _expect_fail(message):
    \"\"\"Record why the build stopped, then stop it.

    The log, not the exception, is the durable record: print() from a
    `abaqus cae noGUI` script does not reach the launcher's stdout, so a
    refusal that only raises leaves selectors.log ending mid-build with no
    reason in it -- which reads as a crash rather than as a check doing its job.
    \"\"\"
    _sel_log(message)
    raise ValueError(message)


def _expect_part(p, part_name, expect):
    \"\"\"Check the built geometry against what the spec says it should be.

    Each named op has a check written behind it -- _cut looks for the hole it
    asked for, because a cut that misses leaves the volume untouched and one
    whose sketch orientation is transposed leaves it EXACTLY right, x and y
    swapped, same element count. A generic call can be any method on Part, so
    nothing here knows what it was supposed to produce and no such check can be
    written.

    So the truth moves to the result. This function is what makes generic
    dispatch safe to offer, and it runs before meshing on purpose.
    \"\"\"
    checks = []
    if 'volume' in expect:
        want = float(expect['volume'])
        tol = float(expect.get('volume_tol', 1.0e-3))
        got = p.getVolume()
        deviation = abs(got - want) / abs(want) if want else abs(got - want)
        if deviation > tol:
            _expect_fail(
                'EXPECT_VOLUME: part %s came out at %s, the spec says %s. Off '
                'by %s, tolerance %s.' % (part_name, got, want, deviation, tol))
        checks.append('volume=%s (want %s, off by %s)' % (got, want, deviation))

    if 'area' in expect:
        # What `volume` is for a solid. It is not interchangeable with it: on a
        # planar part `getVolume()` answers 0.0 without raising -- the same
        # silent zero the IGES shell and the orphan mesh give -- so a 2D part
        # that stated a volume would pass nothing and fail everything.
        want = float(expect['area'])
        tol = float(expect.get('area_tol', 1.0e-3))
        got = p.getArea(p.faces)
        deviation = abs(got - want) / abs(want) if want else abs(got - want)
        if deviation > tol:
            _expect_fail(
                'EXPECT_AREA: part %s came out at %s, the spec says %s. Off '
                'by %s, tolerance %s.' % (part_name, got, want, deviation, tol))
        checks.append('area=%s (want %s, off by %s)' % (got, want, deviation))

    for key, attribute in (('cells', 'cells'), ('faces', 'faces'),
                           ('edges', 'edges'), ('vertices', 'vertices')):
        if key in expect:
            want = int(expect[key])
            got = len(getattr(p, attribute))
            if got != want:
                _expect_fail(
                    'EXPECT_COUNT: part %s has %d %s, the spec says %d.'
                    % (part_name, got, attribute, want))
            checks.append('%s=%d' % (attribute, got))

    found = []
    for f in p.faces:
        try:
            radius = f.getRadius()
        except Exception:
            continue
        found.append((radius, f.getCentroid()[0]))

    if 'cylindrical_faces' in expect:
        want = int(expect['cylindrical_faces'])
        if len(found) != want:
            _expect_fail(
                'EXPECT_COUNT: part %s has %d cylindrical face(s), the spec '
                'says %d. This is the count that catches a cut which silently '
                'missed -- measured on Abaqus 2021, a cut landing off the solid '
                'leaves the volume byte-identical and raises nothing.'
                % (part_name, len(found), want))
        checks.append('cylindrical_faces=%d' % len(found))

    if expect.get('cylinders'):
        # Counts and volume cannot see a cut that landed in the wrong PLACE.
        # Measured on Abaqus 2021: drilling the same hole with the sketch
        # oriented against XAXIS instead of ZAXIS moved it from (0, 5, 20) to
        # (-20, 5, 0) -- 90 degrees away -- with volume 31447.3311 vs
        # 31447.3357 (1.5e-7 apart, which is faceting noise) and faces, edges,
        # vertices and cylindrical_faces all identical. On a symmetric part no
        # global measure can distinguish them, so the position has to be said.
        worst = None
        for entry in expect['cylinders']:
            radius, at, tol = entry[0], entry[1:4], entry[4]
            hit = None
            for candidate_r, centroid in found:
                if abs(candidate_r - radius) > max(1.0e-6, radius * 1.0e-4):
                    continue
                off = max(abs(centroid[0] - at[0]), abs(centroid[1] - at[1]),
                          abs(centroid[2] - at[2]))
                if off <= tol:
                    hit = centroid
                    if worst is None or off / tol > worst[0]:
                        worst = (off / tol, off, tol)
                    break
            if hit is None:
                near = ['r=%s at %s' % (r, c) for r, c in found] or ['none']
                _expect_fail(
                    'EXPECT_CYLINDER: part %s has no cylindrical face of radius '
                    '%s centred at %s (within %s). Cylindrical faces present: '
                    '%s.' % (part_name, radius, tuple(at), tol, '; '.join(near)))
        # How close the closest call came to being refused. A passing check that
        # reports its margin is the only way the default tolerance can ever be
        # retuned on evidence instead of on nerve.
        checks.append('cylinders=%d (worst off by %.6g of %.6g allowed)'
                      % (len(expect['cylinders']),
                         worst[1] if worst else 0.0, worst[2] if worst else 0.0))

    _sel_log('EXPECT_OK: %s %s' % (part_name, ', '.join(checks)))


def _expect_asm_op(m, obj, where, measures):
    \"\"\"What an assembly operation actually made, measured on the result.

    Duck-typed on two facts measured on Abaqus 2021
    (artifacts/probe_asm_op_expect): InstanceFromBooleanCut returns a
    PartInstance that carries partName='Cut' and has NO getVolume, and
    PartFromBooleanMerge returns a Part that carries getVolume and has no
    partName. So the partName branch has to come first, and volume has to be
    read off the part, never off the instance. No list of method names
    anywhere -- a pattern returns a tuple and translate returns an int, and
    both land in the last branch by shape.

    Volume is live without a.regenerate(): measured 7280.0 before and after.
    \"\"\"
    want_volume, volume_tol, want_cells = measures
    if obj is None:
        _expect_fail(
            'ASM_EXPECT_NO_RESULT: %s carries `expect:` and the call returned '
            'nothing to measure. What an operation left behind is checked '
            'without being asked (ASSEMBLY_UNMESHED, PART_NOT_INSTANCED); how '
            'many instances there are and where they landed go in '
            'assembly.expect.' % where)
    if hasattr(obj, 'partName'):
        geom = m.parts[obj.partName]
        label = 'instance of part %s' % obj.partName
    elif hasattr(obj, 'getVolume'):
        geom = obj
        label = 'part %s' % getattr(obj, 'name', '?')
    else:
        _expect_fail(
            'ASM_EXPECT_UNMEASURABLE: %s carries `expect:` and the call '
            'returned a %s, which is neither a part nor an instance, so there '
            'is no single body to measure. A pattern makes many: state '
            'assembly.expect.instances for how many and assembly.expect.at '
            'for where each landed.' % (where, type(obj).__name__))
    checks = []
    if want_volume is not None:
        got = geom.getVolume()
        off = abs(got - want_volume) / abs(want_volume)
        if off > volume_tol:
            _expect_fail(
                'ASM_EXPECT_VOLUME: %s produced %s of volume %s, the spec says '
                '%s. Off by %s, tolerance %s. A boolean that joins nothing is '
                'silent: measured on Abaqus 2021, a merge of two bodies that '
                'do not touch keeps every cubic millimetre of both and the '
                'instance count, the wire count and every centroid come out '
                'the same as for one that worked.'
                % (where, label, got, want_volume, off, volume_tol))
        checks.append('volume=%s' % got)
    if want_cells is not None:
        got = len(geom.cells)
        if got != want_cells:
            _expect_fail(
                'ASM_EXPECT_CELLS: %s produced %s with %d cell(s), the spec '
                'says %d. Measured on Abaqus 2021: a merge of two bodies that '
                'do not touch returns TWO cells and the full volume of both, '
                'so what solves is two loose pieces where the spec asked for '
                'one solid -- the cell count is the only one of the two '
                'measures that sees it.' % (where, label, got, want_cells))
        checks.append('cells=%d' % got)
    _sel_log('ASM_EXPECT_OK: %s -- %s' % (where, ', '.join(checks)))


def _expect_recorded(result, where, keys):
    \"\"\"A call handed a sequence of exactly one, which then recorded nothing.

    Measured on Abaqus 2021 (artifacts/probe_position_seq/probe_out.txt): the
    four positioning constraints -- FaceToFace, ParallelFace, EdgeToEdge,
    CoincidentPoint -- handed the GeomSequence that {select:} compiles to all
    return None, add nothing to a.features, grow no repository, and leave the
    instance exactly where it was, before and after a.regenerate(). Handed the
    entity itself they return a named Feature and move it 40.0 / 10.0 / 30.0 /
    30.0 mm. Nothing downstream can tell those two runs apart.

    Return value, not "did anything change": also measured, makeIndependent
    and seedPartInstance change no repository and move nothing, and they are
    the documented way to mesh a boolean result. A rule about change would
    refuse the escape hatch.
    \"\"\"
    if result is not None:
        return result
    _expect_fail(
        'CALL_RECORDED_NOTHING: %s was handed %s as a SEQUENCE of exactly one '
        '-- select: always compiles to a sequence -- and the call returned '
        'nothing and recorded nothing, so nothing downstream can see that it '
        'did nothing. Measured on Abaqus 2021: a positioning constraint given '
        'that sequence leaves the instance where it was and the deck still '
        'goes green. Pass the entity itself with {one: \"<instance>:face@...\"}, '
        'or say a sequence was meant with {select: \"<plural>\", expect: \"=1\"}.'
        % (where, keys))


def _gone(found, label):
    \"\"\"The one entity a selector names, not the sequence holding it.

    Belt and braces: _sel_resolve already raises SELECTOR_MISMATCH first,
    because {one:} forces the count assertion to '=1'. This catches the case
    where a future selector path returns without that check.
    \"\"\"
    if len(found) != 1:
        _expect_fail('ONE_NOT_SINGLE: %s named %d entities; this argument '
                     'takes exactly one.' % (label, len(found)))
    return found[0]


'''

# resolvers -- name a vertex, wire, surface, set, seam, point
_H_RESOLVERS = '''\
def _gvertex(a, instance, point, label):
    \"\"\"The one vertex of an instance at this position.

    Counted, like every other selection: findAt on a point where there is no
    vertex returns an empty sequence, and WirePolyLine would then be handed
    nothing and build a wire attached at one end.
    \"\"\"
    if instance not in a.instances.keys():
        _expect_fail('VERTEX_NO_INSTANCE: %s wants a vertex of %s, which the '
                     'assembly does not have. Present: %s.'
                     % (label, instance, ', '.join(sorted(a.instances.keys()))))
    found = a.instances[instance].vertices.findAt((point,))
    if len(found) != 1:
        _expect_fail('VERTEX_NOT_FOUND: %s wants the vertex of %s at %s and '
                     'found %d. A wire endpoint has to land on a real corner: '
                     'a wire built from a bare coordinate is accepted and then '
                     'fails in the solver with "CONNECTOR ELEMENT ... NODE '
                     'NUMBERS CANNOT BE BOTH ZERO".'
                     % (label, instance, point, len(found)))
    _sel_log('VERTEX_OK: %s %s at %s' % (label, instance, point))
    return found[0]


def _gwire(a, first, second, label):
    \"\"\"The assembly edge running between these two points.

    Wire edges are on the root assembly, not on any instance: measured, an
    assembly with two instances and four wires had len(a.edges) == 4 while
    len(a.instances['Fixed'].edges) == 12. So this cannot go through the
    ordinary selector, and the midpoint of the segment that made the wire is
    what finds it.
    \"\"\"
    mid = ((first[0] + second[0]) / 2.0, (first[1] + second[1]) / 2.0,
           (first[2] + second[2]) / 2.0)
    found = a.edges.findAt((mid,))
    if len(found) != 1:
        _expect_fail('WIRE_NOT_FOUND: %s expected one wire between %s and %s '
                     '(looking at %s) and found %d. The assembly has %d edge(s) '
                     'in total.'
                     % (label, first, second, mid, len(found), len(a.edges)))
    _sel_log('WIRE_OK: %s between %s and %s' % (label, first, second))
    return found


def _expect_connectors(m, a, want_wires=None):
    \"\"\"Every wire has to carry a section, and there is no reason it would not.

    Measured on Abaqus 2021, four corner springs of k = 25 between two blocks
    under a 1000 N pull:

        4 wires, 4 sections assigned -> U3 = 10.0018 (F/k = 10.000)
        4 wires, 3 sections assigned -> U3 = 13.3357 (F/k = 13.333)

    The second job COMPLETED with no error and no warning. One missing section
    assignment is a quarter of the stiffness gone and nothing anywhere says so
    -- the wire is still there, still drawn, still in the model tree. Unlike the
    tie gap there is no number to state: a wire without a section is never what
    anybody meant, so this needs nothing from the spec.
    \"\"\"
    wires = len(a.edges)
    if want_wires is not None and wires != want_wires:
        _expect_fail('EXPECT_WIRES: the assembly has %d wire(s), the spec says '
                     '%d.' % (wires, want_wires))
    if not wires:
        return
    covered = {}
    for assignment in a.sectionAssignments:
        region = assignment.region
        edges = None
        try:
            edges = region.edges
        except Exception:
            try:
                edges = a.sets[str(region[0])].edges
            except Exception:
                edges = None
        if edges is None:
            continue
        for edge in edges:
            covered[edge.index] = str(assignment.sectionName)
    missing = [e.index for e in a.edges if e.index not in covered]
    if missing:
        _expect_fail('WIRE_UNASSIGNED: %d of %d wire(s) carry no section '
                     '(edge index %s). A wire with no section contributes '
                     'nothing, and the job still completes: measured, dropping '
                     'one of four springs moved the answer from 10.0018 to '
                     '13.3357 with no error and no warning.'
                     % (len(missing), wires,
                        ', '.join(str(i) for i in missing)))
    _sel_log('EXPECT_OK: %d wire(s), all carrying a section (%s)'
             % (wires, ', '.join(sorted(set(covered.values())))))


def _expect_sections(p, part_name):
    \"\"\"Every cell of a part has to carry a section.

    Only emitted when the spec assigned sections itself. On the default path
    the builder assigns one section to every cell and there is nothing to
    check; here the spec named some regions and the rest is unknown.

    Leaving a cell unassigned is not silent -- Abaqus stops with '***ERROR: n
    elements have missing property definitions' -- but that arrives after the
    whole build and the whole submit, and it names elements, which the spec
    never mentioned. This says which part, at build time, in the spec's own
    vocabulary.

    Faces are used instead of cells on a shell part, where p.cells is empty.
    \"\"\"
    entities = list(p.cells)
    kind = 'cell'
    if not entities:
        entities = list(p.faces)
        kind = 'face'
    if not entities:
        return
    covered = {}
    for assignment in p.sectionAssignments:
        region = assignment.region
        found = None
        for attr in ('cells', 'faces'):
            try:
                found = getattr(region, attr)
            except Exception:
                found = None
            if found:
                break
        if not found:
            # A Region given as a set name comes back as a bare tuple.
            try:
                found = getattr(p.sets[str(region[0])], kind + 's')
            except Exception:
                found = None
        if not found:
            continue
        for entity in found:
            covered[entity.index] = str(assignment.sectionName)
    missing = [e.index for e in entities if e.index not in covered]
    if missing:
        _expect_fail('SECTION_UNASSIGNED: part %r has %d %s(s) with no section '
                     '(index %s of %d). The spec assigns its own sections, so '
                     'nothing covers the rest; Abaqus would stop later with '
                     '\"elements have missing property definitions\".'
                     % (part_name, len(missing), kind,
                        ', '.join(str(i) for i in missing[:8]), len(entities)))
    _sel_log('SECTION_OK: %s %d %s(s) covered by %s'
             % (part_name, len(entities), kind,
                ', '.join(sorted(set(covered.values())))))


def _gsurface(a, name, geometry, kwarg, label):
    \"\"\"Create the assembly surface an interaction argument asked for.

    Surface() does return the new surface, and passing that object straight
    into Tie was measured to solve correctly -- but `Surface(...) is
    a.surfaces[name]` comes back False, so the two are different wrappers over
    the same thing. Reading it back out of the repository means one canonical
    object, and it also puts the surface under a name that appears in the .dat
    and in the solver's own warnings, which is where anyone debugging will be
    looking.
    \"\"\"
    if name in a.surfaces.keys():
        _expect_fail('SURFACE_DUPLICATE: %s wants to create surface %s, which '
                     'already exists. Give it a name: of its own.'
                     % (label, name))
    a.Surface(**{'name': name, kwarg: geometry})
    surface = a.surfaces[name]
    try:
        count = len(surface.nodes)
    except Exception:
        count = -1
    _sel_log('SURFACE_OK: %s %s (%s, %d node(s))' % (label, name, kwarg, count))
    return surface


def _gset(a, name, geometry, kwarg, label):
    \"\"\"Create the assembly set a condition asked for, and count its nodes.

    The node count is logged whether or not the spec asked, because it is the
    difference between the load written and the load applied. Measured on
    Abaqus 2021, `cf2=-100` on a set of the four tip corners of a cantilever:
    total reaction 400 N, tip -0.7584553; the same call at cf2=-25 on the
    same four nodes, 100 N and -0.1896138. Both jobs COMPLETED with no
    warning. A concentrated load is written per node, so the magnitude in the
    spec is not the load unless the set holds exactly one node.

    A pressure is per AREA and does not have this problem, which is why the
    count is reported rather than refused outright.
    \"\"\"
    if name in a.sets.keys():
        _expect_fail('SET_DUPLICATE: %s wants to create set %s, which already '
                     'exists. Give it a name: of its own.' % (label, name))
    a.Set(**{'name': name, kwarg: geometry})
    built = a.sets[name]
    try:
        nodes = len(built.nodes)
    except Exception:
        nodes = -1
    _sel_log('SET_OK: %s %s (%s, %d node(s))' % (label, name, kwarg, nodes))
    return built


def _gimported(m, want, before, label):
    \"\"\"The part a model method just made, under the name the spec gave it.

    Measured on Abaqus 2021 (artifacts/probe_orphan), `PartFromInputFile`
    takes no `name` argument at all: the deck names the part and Abaqus
    UPPER-CASES it, so a deck whose part is `Bar` arrives as `BAR`, and a deck
    holding two arrives as `ALPHA` and `BETA`. Every other line in this script
    names the part from the spec, so the name is taken back here --
    `parts.changeKey` was measured to do it -- and a file that produced
    anything other than exactly one part is refused rather than guessed at,
    because picking one of two would be picking for the author.
    \"\"\"
    made = [name for name in m.parts.keys() if name not in before]
    if len(made) != 1:
        _expect_fail(
            'IMPORT_PART_COUNT: %s made %d part(s) (%s) and a spec names one. '
            'A deck holding several parts has to be split, or the spec has to '
            'name each one.'
            % (label, len(made), ', '.join(sorted(made)) or 'none'))
    got = made[0]
    if got != want:
        if want in m.parts.keys():
            _expect_fail(
                'IMPORT_NAME_TAKEN: %s produced part %s and the spec calls it '
                '%s, which already exists in this model.' % (label, got, want))
        m.parts.changeKey(fromName=got, toName=want)
    p = m.parts[want]
    _sel_log('IMPORT_OK: %s -> %s (was %s): %d node(s), %d element(s), '
             '%d cell(s)' % (label, want, got, len(p.nodes), len(p.elements),
                             len(p.cells)))
    return p


def _expect_seam(p, set_name, wanted, label):
    \"\"\"Did the seam actually separate anything?

    It has to be asked, because the way it fails is silent. Measured on Abaqus
    2021 (artifacts/probe_seam2), one 10 x 10 x 10 block partitioned at
    mid-height and meshed at seed 5:

        no seam                     27 nodes
        seam on the INTERIOR face   36 nodes
        seam on the top face        27 nodes   <- assignSeam returned, no error
        seam on the bottom face     27 nodes   <- assignSeam returned, no error

    A face that is not shared by two cells cannot be separated, and Abaqus does
    not say so. Picking the wrong face with a selector is an ordinary mistake,
    and what comes out is a model with no crack in it that builds, solves and
    reports success.

    The observable is the seam's own set. Measured on the interior case it
    holds 18 nodes at 9 distinct positions -- two per position -- where an
    unseamed face gives 9 at 9. So the count of positions carrying more than
    one node is the seam, and it is compared against what the spec stated.
    \"\"\"
    if set_name not in p.sets.keys():
        _expect_fail('SEAM_NO_SET: %s expects a seam on set %s, which is not '
                     'on this part. Sets here: %s'
                     % (label, set_name,
                        ', '.join(sorted(p.sets.keys())) or 'none'))
    nodes = p.sets[set_name].nodes
    if len(nodes) == 0:
        _expect_fail(
            'SEAM_NO_NODES: %s expects a seam on set %s and the set holds no '
            'nodes. A seam is counted after the mesh exists, so this means '
            'the part was never meshed, or the set is on geometry the mesh '
            'did not reach.' % (label, set_name))
    seen = {}
    for node in nodes:
        c = node.coordinates
        key = '%.6f_%.6f_%.6f' % (c[0], c[1], c[2])
        seen[key] = seen.get(key, 0) + 1
    positions = len(seen)
    duplicated = len([k for k in seen if seen[k] > 1])
    if duplicated != wanted:
        _expect_fail(
            'SEAM_NOT_SEPARATED: %s expected %d duplicated node position(s) '
            'on set %s and found %d (%d node(s) at %d position(s)). Zero '
            'means the seam was accepted and changed nothing, which is what '
            'happens on a face that is not shared by two cells -- measured on '
            'Abaqus 2021, the same block gives 27 nodes with such a seam and '
            '36 with a correct one, and neither raises.'
            % (label, wanted, set_name, duplicated, len(nodes), positions))
    _sel_log('SEAM_OK: %s %s -> %d node(s) at %d position(s), %d duplicated'
             % (label, set_name, len(nodes), positions, duplicated))


def _grp(a, name, point, label, at=None):
    \"\"\"Make the reference point a Coupling, RigidBody or MPC controls, and log it.

    Three things had to be measured before this could be written, all on
    Abaqus 2021 (artifacts/probe_rp):

    WHAT IT RETURNS. `a.ReferencePoint(point=...)` hands back a Feature, not a
    point. The reference point itself is `a.referencePoints[feature.id]`, and
    what a constraint wants is a REGION over that -- so the round trip is three
    objects, none of which a spec could name.

    WHAT THE DECK CARRIES. A Set built here is what the card names:
    `*Coupling, constraint name=Cpl, ref node=RP, surface=TIPFACE`. So the set
    name is not bookkeeping; it is what somebody reads in the input file.

    AND WHY THE POSITION IS LOGGED. A control point in the wrong place is
    silent from end to end. Same bar, same 100 N on the reference point, only
    the point moved -- read two ways, because the reference point is itself a
    node and the two readings come apart (scripts/run_reference_point_check.py,
    beam theory -0.19047619):

                                   whole model       tip face only
        (5, 5, 100) centre of      -0.18944125       -0.18944125    0.5% out
                    the tip face
        (5, 5, 150) 50 mm past     -0.61471903       -0.33120051    223% / 74%
                    the end

    The second row reported 0 errors, 0 warnings and COMPLETED. Note which
    column a spec actually gets: `location: whole_model` is answered about the
    reference point, a node that is not part of the structure, so the wrongest
    of the two numbers is the one handed back. Nothing refuses it here, because
    an offset control point is a legitimate way to apply a moment -- the point
    that is wrong and the point that is deliberate look identical. What this
    can do is put the position in the record, so "which point was it?" has an
    answer that is not a re-run.
    \"\"\"
    if name in a.sets.keys():
        _expect_fail('SET_DUPLICATE: %s wants to create set %s, which already '
                     'exists. Give it a name: of its own.' % (label, name))
    feature = a.ReferencePoint(point=point)
    rp = a.referencePoints[feature.id]
    built = a.Set(**{'name': name, 'referencePoints': (rp,)})
    held = len(built.referencePoints)
    if held != 1:
        _expect_fail(
            'REFERENCE_POINT_NOT_ONE: %s built set %s holding %d reference '
            'points. A Coupling, a RigidBody and an MPC each control exactly '
            'one; anything else is not the region they mean.'
            % (label, name, held))
    where = '' if at is None else (' at the centroid of %s' % at)
    _sel_log('REFERENCE_POINT_OK: %s %s at (%.6g, %.6g, %.6g)%s'
             % (label, name, point[0], point[1], point[2], where))
    return built


def _gnamed(a, name, label):
    \"\"\"The set an earlier call in this spec already built, by name.

    Every other region form re-finds its region by geometry. A reference point
    cannot be re-found: it lies on no face and no edge, so no selector reaches
    it. Naming the set the earlier call created is therefore the only way a
    second call can act on the point a coupling controls -- and that second
    call is the whole reason the first one exists, because a control point
    nothing loads is a control point nothing tests.

    Checked here rather than at generation because the set registry is built
    per call, so no earlier stage can see across two of them. The kernel can:
    it is holding the assembly.
    \"\"\"
    if name in a.sets.keys():
        _sel_log('NAMED_SET_OK: %s -> %s' % (label, name))
        return a.sets[name]
    if name in a.surfaces.keys():
        _expect_fail(
            'NAMED_SET_IS_A_SURFACE: %s names %s, which exists on this '
            'assembly as a SURFACE. A surface is faces and a set is nodes, and '
            'a load or a boundary condition wants the set. Sets here: %s'
            % (label, name, ', '.join(sorted(a.sets.keys())) or 'none'))
    _expect_fail(
        'NAMED_SET_MISSING: %s names set %s, which no earlier call in this '
        'spec created. A set is created by the call that first uses it, so a '
        'name can only be reused AFTER that call, never before. Sets on the '
        'assembly at this point: %s'
        % (label, name, ', '.join(sorted(a.sets.keys())) or 'none'))


def _rp_centroid(entity, label, raw):
    \"\"\"Where to put a reference point that the spec placed by selector.

    getCentroid() returns a one-tuple of a coordinate triple, and it is a
    TESSELLATION ESTIMATE -- measured elsewhere in this file at 0.070931 mm off
    on a bore of r = 300. That error is the reason `expect.cylinders[].at` has
    a scale-relative tolerance. It does NOT carry the same weight here: a
    reference point is a modelling decision, not a measurement, and on a planar
    face the estimate is the exact centre. Recorded so nobody later reads this
    as a measured position.
    \"\"\"
    try:
        got = entity.getCentroid()
    except Exception as exc:
        _expect_fail(
            'REFERENCE_POINT_NO_CENTROID: %s asked for the centroid of %s and '
            'the entity has none (%s: %s). Give the point as three numbers '
            'instead.' % (label, raw, type(exc).__name__, exc))
    nested = (isinstance(got, (list, tuple)) and got
              and isinstance(got[0], (list, tuple)))
    point = got[0] if nested else got
    return (float(point[0]), float(point[1]), float(point[2]))


def _expect_points(a, set_name, wanted, label):
    \"\"\"How many nodes the load really lands on.

    Stated by the spec because a per-node load multiplies by exactly this
    number and nothing in the job says so.
    \"\"\"
    if set_name not in a.sets.keys():
        _expect_fail('POINTS_NO_SET: %s expects %d point(s) in set %s, which '
                     'does not exist. Present: %s.'
                     % (label, wanted, set_name,
                        ', '.join(sorted(a.sets.keys())) or 'none'))
    found = len(a.sets[set_name].nodes)
    if found != wanted:
        _expect_fail(
            'POINTS_MISMATCH: %s applies to %d node(s) in set %s, the spec '
            'says %d. A concentrated load is written PER NODE: measured on '
            'Abaqus 2021, cf2=-100 on four corners totals 400 N and the job '
            'completes without a warning.'
            % (label, found, set_name, wanted))
    _sel_log('POINTS_OK: %s %s has %d node(s)' % (label, set_name, found))


'''

# deck -- the truth layer that reads the emitted .inp
_H_DECK = '''\
def _expect_cload(a, inp_path, stated):
    \"\"\"Every *Cload the input file carries, and how many nodes it lands on.

    Read out of the file Abaqus just wrote, rather than guessed from the shape
    of the selector. A concentrated force and a moment both write *Cload, and
    so will whatever the next release adds; nothing here has to know which
    calls those are.

    Two measurements make this the only place the check can live.

    The magnitude is PER NODE. On a 10x10x100 cantilever, cf2=-100 on a set of
    the four tip corners: total reaction 400 N, tip -0.7584553 mm. The same
    call at cf2=-25 on the same four nodes: 100 N, -0.1896138, which is
    P L^3 / (3 E I) to 0.45%. Both COMPLETE with no warning.

    And CAE's own guard does not run here. Submitting a concentrated force on a
    face-based set from CAE is refused outright -- "contains invalid geometry
    or mesh components for the load type", and no input file is written. But
    this deck calls writeInput(consistencyChecking=OFF), so that check is
    skipped and the card comes out as `*Cload / TIP, 2, -100.` against an Nset
    of four nodes. The solver then applies 400 N and reports success.

    The input file is removed before this raises: leaving it behind would let
    a caller that tests for its existence treat a refused build as a good one.
    \"\"\"
    try:
        handle = open(inp_path)
        try:
            lines = handle.read().splitlines()
        finally:
            handle.close()
    except Exception:
        _sel_log('CLOAD_UNREADABLE: %s' % inp_path)
        return

    targets = []
    index = 0
    while index < len(lines):
        if lines[index].strip().lower().startswith('*cload'):
            index += 1
            while index < len(lines) and not lines[index].lstrip().startswith('*'):
                body = lines[index].strip()
                if body:
                    targets.append(body.split(',')[0].strip())
                index += 1
            continue
        index += 1

    problems = []
    for name in targets:
        try:
            count = len(a.sets[name].nodes)
        except Exception:
            # A bare node number, or a set this side cannot see. Reported
            # rather than guessed at.
            _sel_log('CLOAD_UNKNOWN_SET: %s' % name)
            continue
        if count <= 1:
            _sel_log('CLOAD_OK: %s lands on %d node(s)' % (name, count))
            continue
        want = stated.get(name)
        if want is None:
            problems.append(
                '%s lands on %d node(s) and the spec never said so'
                % (name, count))
        elif want != count:
            problems.append('%s lands on %d node(s), the spec says %d'
                            % (name, count, want))
        else:
            _sel_log('CLOAD_OK: %s lands on %d node(s), as stated, so the '
                     'total is %d x the magnitude written' % (name, count, count))
    if problems:
        try:
            os.remove(inp_path)
        except Exception:
            pass
        _expect_fail(
            'CLOAD_PER_NODE: %s. A concentrated load is written PER NODE, so '
            'the magnitude in the spec is not the load applied -- measured on '
            'Abaqus 2021, cf2=-100 on four corners totals 400 N and the job '
            'completes without a warning. State the count with '
            '`expect: {points: N}` and divide the magnitude yourself.'
            % '; '.join(problems))


def _expect_keywords(inp_path, wanted):
    \"\"\"Every line a keywordBlock insert asked for is in the file that was written.

    `m.keywordBlock` is the escape hatch: a card this dialect has no name for,
    typed as text and spliced into the deck. Everything else in the deck is
    checked by asking the model what it contains; a keyword block cannot be,
    because the model has no opinion about text. So the only available check is
    to read the input file back and look for it.

    What was measured on Abaqus 2021 (artifacts/probe_keyword_block), and it
    is NOT what this was written expecting. `position` names a block in
    keywordBlock.sieBlocks and the text goes AFTER that block, so what the
    integer lands on decides everything:

      insert(21), after *Elastic    card in the deck, no conflict block,
                                    datacheck 0 errors -- the escape hatch
                                    working, a *Damping card CAE has no field
                                    for reaching the solver
      insert(3), inside *Element    card in the deck, KEYWORD_OK logged, and
                                    the deck is wrapped in *Conflicts: 4 FATAL
                                    ERRORS, EXECUTION IS TERMINATED
      insert(1), after *Part        card in the deck, no conflict block, 1
                                    fatal error -- *Damping is not legal there
      insert(100000)                IndexError, build aborts
      insert(-5)                    IndexError, build aborts
      no synchVersions first        card in the deck -- not required on this
                                    model, contrary to what was assumed
      synchVersions after insert    card still in the deck -- a later
                                    synchronise did not discard the edit

    So the missing-card case this was written for has never been observed, and
    a worse one has: the card arrives, this check says KEYWORD_OK, and the deck
    is unreadable. That is what the *Conflicts test below is for, and it is the
    verified counterexample the read-back itself still lacks. The read-back is
    kept because it costs nothing on top of a file read that now has to happen
    anyway.

    What neither test can see is insert(1): conflict-free, in the deck, and
    illegal where it landed. Only the input file processor knows that, and it
    says so loudly when the job runs -- so it is left to the job rather than
    guessed at here.

    Compared with whitespace squeezed and case folded, because Abaqus rewrites
    a card's spacing and capitalisation freely -- a literal comparison would
    refuse decks that carry exactly what was asked for.

    The input file is removed before this raises, for the same reason
    _expect_cload removes it: a caller that tests for its existence must not
    read a refused build as a good one.
    \"\"\"
    if not wanted:
        return
    try:
        handle = open(inp_path)
        try:
            deck = handle.read()
        finally:
            handle.close()
    except Exception:
        _sel_log('KEYWORDS_UNREADABLE: %s' % inp_path)
        return

    squeezed = ' '.join(deck.split()).upper()
    missing = []
    for where, text in wanted:
        needle = ' '.join(str(text).split()).upper()
        if needle and needle not in squeezed:
            missing.append('%s asked for %r' % (where, text))
        else:
            _sel_log('KEYWORD_OK: %s is in the deck' % where)
    if missing:
        try:
            os.remove(inp_path)
        except Exception:
            pass
        _expect_fail(
            'KEYWORD_NOT_WRITTEN: %s, and the written input file does not '
            'contain it. The call itself did not raise, so the card was '
            'accepted by the block and then did not reach the deck -- the job '
            'would have run without it. Measured on Abaqus 2021, an out-of-'
            'range position raises IndexError instead, so this is not that: '
            'look at what the block held when the insert ran.'
            % '; '.join(missing))

    if '*CONFLICTS' in squeezed:
        try:
            os.remove(inp_path)
        except Exception:
            pass
        _expect_fail(
            'KEYWORD_CONFLICT_BLOCK: the card is in the deck and the deck '
            'cannot be read. CAE wrapped the edit in a *Conflicts block, which '
            'is not an analysis keyword -- Abaqus/Standard reports it as a '
            'fatal input error and stops before the first increment. Measured '
            'on Abaqus 2021 with the same card and the same spec: insert after '
            'block 21 (the end of *Elastic) datachecks with 0 errors, insert '
            'after block 3 (inside the generated *Element table) produces this '
            'block and 4 FATAL ERRORS. A position must name the end of a '
            'block, not a line inside one; enumerate keywordBlock.sieBlocks to '
            'see where the boundaries are.')


def _expect_steps(m, wanted):
    \"\"\"The analysis runs the steps in the order the spec wrote them.

    Not a formality. Measured on Abaqus 2021: two StaticSteps both declaring
    `previous='Initial'` are BOTH accepted, and the second one is inserted
    BEFORE the first -- m.steps comes out ('Initial', 'Two', 'One') and the ODB
    agrees. The job completes. A preload-then-load analysis written in the
    obvious order runs backwards and nothing says so.
    \"\"\"
    got = [name for name in m.steps.keys() if name != 'Initial']
    if got != list(wanted):
        _expect_fail(
            'STEP_ORDER: the analysis runs %s, the spec wrote %s. Abaqus '
            'inserts a step after the one named in `previous:`, so two steps '
            'that both follow Initial come out in the reverse of the order '
            'they were written -- measured, and the job still completes.'
            % (' -> '.join(got) or 'nothing', ' -> '.join(wanted)))
    _sel_log('STEP_ORDER_OK: %s' % (' -> '.join(got) or 'nothing'))


'''

# assembly -- gaps, placement, instances, assembly-level meshing
_H_ASSEMBLY = '''\
def _surface_gap(a, main_name, secondary_name):
    \"\"\"Worst distance from a secondary-surface node to the nearest main node.

    Node-to-node, while Abaqus ties node-to-SURFACE. That asymmetry is the safe
    direction: this can over-report a gap and refuse something that would have
    worked, but it cannot report zero for a pair that is really apart.

    Bucketed onto a grid because the honest version is O(n*m): 156x156 measured
    at 9 ms, but surfaces of a few thousand nodes each would be minutes. Cells
    are searched outward from the secondary node's own cell and the scan falls
    back to every main node when the neighbourhood is empty, so bucketing
    changes the speed and not the answer.
    \"\"\"
    main_nodes = [n.coordinates for n in a.surfaces[main_name].nodes]
    sec_nodes = [n.coordinates for n in a.surfaces[secondary_name].nodes]
    if not main_nodes or not sec_nodes:
        return {'empty': True, 'n_main': len(main_nodes), 'n_sec': len(sec_nodes)}

    lo = [min(p[i] for p in main_nodes) for i in (0, 1, 2)]
    hi = [max(p[i] for p in main_nodes) for i in (0, 1, 2)]
    span = max(hi[0] - lo[0], hi[1] - lo[1], hi[2] - lo[2], 1.0e-9)
    cell = span / 24.0
    buckets = {}
    for q in main_nodes:
        key = (int((q[0] - lo[0]) / cell), int((q[1] - lo[1]) / cell),
               int((q[2] - lo[2]) / cell))
        if key not in buckets:
            buckets[key] = []
        buckets[key].append(q)

    def nearest(s):
        base = (int((s[0] - lo[0]) / cell), int((s[1] - lo[1]) / cell),
                int((s[2] - lo[2]) / cell))
        best = None
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                for dz in (-1, 0, 1):
                    for q in buckets.get((base[0] + dx, base[1] + dy,
                                          base[2] + dz), ()):
                        d2 = ((s[0] - q[0]) ** 2 + (s[1] - q[1]) ** 2
                              + (s[2] - q[2]) ** 2)
                        if best is None or d2 < best:
                            best = d2
        if best is None:
            for q in main_nodes:
                d2 = ((s[0] - q[0]) ** 2 + (s[1] - q[1]) ** 2
                      + (s[2] - q[2]) ** 2)
                if best is None or d2 < best:
                    best = d2
        return best

    worst = 0.0
    for s in sec_nodes:
        d2 = nearest(s)
        if d2 is not None and d2 > worst:
            worst = d2
    return {'empty': False, 'worst': worst ** 0.5,
            'n_main': len(main_nodes), 'n_sec': len(sec_nodes)}


def _expect_gap(a, label, main_name, secondary_name, low, high):
    \"\"\"How far apart the two surfaces of a pair actually are.

    Measured on Abaqus 2021, on a two-layer cantilever with both layers built
    in at the root and pressure on top:

        gap 0.00, tolerance 0.01 -> tie holds,      tip U3 = -0.3533
        gap 0.05, tolerance 0.01 -> tie holds NOTHING, tip U3 = -2.8094

    The second job COMPLETED SUCCESSFULLY. Same deck, same *Tie card, same
    position tolerance printed in the .dat; the layers simply slid over each
    other and the answer came out 7.95x too large -- which is what losing one of
    two bonded layers does to a bending stiffness. Abaqus does say something
    ("*TIE ... IS REVERTED ... CANNOT FIND NODES TO TIE TOGETHER" in the .dat,
    "2 UNCONNECTED REGIONS" in the .msg) but both are warnings in a job that
    reports success, and by then the solve has already been paid for.

    So the pair is measured here, before the job is written, from the node
    coordinates of the two surfaces.
    \"\"\"
    for wanted in (main_name, secondary_name):
        if wanted not in a.surfaces.keys():
            _expect_fail('GAP_NO_SURFACE: %s asks about surface %s, which the '
                         'assembly does not have. Present: %s.'
                         % (label, wanted,
                            ', '.join(sorted(a.surfaces.keys())) or 'none'))
    found = _surface_gap(a, main_name, secondary_name)
    if found['empty']:
        _expect_fail('GAP_UNMEASURABLE: %s -- surface %s has %d node(s) and %s '
                     'has %d. A gap is measured from the mesh, so both parts '
                     'have to be meshed before the interaction is made.'
                     % (label, main_name, found['n_main'], secondary_name,
                        found['n_sec']))
    worst = found['worst']
    if high is not None and worst > high:
        _expect_fail('EXPECT_GAP: %s -- %s and %s are up to %.6g apart, the '
                     'spec allows %.6g. A pair wider than its position '
                     'tolerance is created without complaint and the job still '
                     'reports success; it just binds nothing.'
                     % (label, main_name, secondary_name, worst, high))
    if low is not None and worst < low:
        _expect_fail('EXPECT_GAP: %s -- %s and %s are only %.6g apart, the spec '
                     'says at least %.6g.'
                     % (label, main_name, secondary_name, worst, low))
    _sel_log('EXPECT_OK: gap %s..%s = %.6g (%d/%d nodes)'
             % (main_name, secondary_name, worst, found['n_main'],
                found['n_sec']))


def _expect_asm_meshed(m, a, before):
    \"\"\"What assembly.operations left behind, and whether it reaches the solver.

    Parts are built and meshed before the assembly exists, so anything an
    operation creates is born unmeshed and nothing downstream meshes it. Two
    shapes of that, both measured on Abaqus 2021 (artifacts/probe59):

    InstanceFromBooleanCut makes part 'Cut' (cells=1, elements=0, nodes=0) and
    instance 'Cut-1' pointing at it, and suppresses the instances it consumed.
    The .inp then carries `*Part, name=Cut` / `*End Part` with a live
    `*Instance` and not one `*Element` in the file, and the job completes.

    PartFromBooleanMerge is quieter: it returns a Part, adds it to m.parts, and
    creates NO instance and suppresses nothing. a.instances is untouched, both
    originals stay meshed, and the analysis that runs is the one from before
    the merge -- two loose pieces where the spec asked for one solid.

    So instances are asked for elements and m.parts is diffed for orphans. The
    instance is asked, never the part: measured, a dependent instance reports
    its part's count (8 = 8, before and after a.regenerate), while an
    independent one meshed at assembly level reports 739 with its part still
    reading 0. Suppression is read off a.features[name], not the instance --
    excludedFromSimulation was False on all three instances after a cut,
    including the two the cut had suppressed.
    \"\"\"
    live = []
    for name in sorted(a.instances.keys()):
        try:
            if a.features[name].isSuppressed():
                continue
        except KeyError:                       # not every instance is a feature
            pass
        live.append(name)

    empty = [n for n in live if len(a.instances[n].elements) == 0]
    if empty:
        _expect_fail(
            'ASSEMBLY_UNMESHED: instance(s) %s carry no elements after '
            'assembly.operations ran. An unmeshed instance reaches the input '
            'file as an empty *Part and the job completes without a word, '
            'contributing no mass and no stiffness. Nothing meshes a part an '
            'operation created -- parts are meshed before the assembly '
            'exists. Mesh it in the same operations block: measured on Abaqus '
            '2021, makeIndependent then setMeshControls + seedPartInstance + '
            'generateMesh on the new instance gave it 739 elements.'
            % ', '.join(empty))

    used = {}
    for name in live:
        used[a.instances[name].partName] = name
    orphans = [p for p in sorted(m.parts.keys())
               if p not in before and p not in used]
    if orphans:
        _expect_fail(
            'PART_NOT_INSTANCED: assembly.operations created part(s) %s, and '
            'nothing instances any of them, so none of them reach the '
            'analysis. Measured on Abaqus 2021: PartFromBooleanMerge returns '
            'a Part, creates no instance at all, and does not suppress the '
            'instances it merged -- so the model that solves is the one you '
            'had before the merge. Instance it in the same operations block, '
            'or do not create it.' % ', '.join(orphans))

    _sel_log('ASSEMBLY_MESH_OK: %d live instance(s), %d created part(s)'
             % (len(live), len(set(m.parts.keys()) - before)))


def _expect_instances(a, want):
    \"\"\"How many instances the assembly ends up with.

    A pattern is the reason this exists. RadialInstancePattern(number=8) that
    produced nothing would leave a model that meshes and solves -- with one
    bolt instead of eight, and a stiffness quietly wrong by a factor nobody
    would question.
    \"\"\"
    got = len(a.instances)
    if got != want:
        names = ', '.join(sorted(a.instances.keys()))
        message = ('EXPECT_INSTANCES: the assembly has %d instance(s), the '
                   'spec says %d. Present: %s.' % (got, want, names))
        _sel_log(message)
        raise ValueError(message)
    _sel_log('EXPECT_OK: assembly instances=%d' % got)


def _expect_placed(a, entries):
    \"\"\"Where each named instance actually ended up, in assembly space.

    Positioning by constraint (FaceToFace and friends) has no return value to
    check and no exception when it does nothing useful, so the only honest test
    is to ask afterwards where the thing is. The box comes from the instance,
    which reports it in ASSEMBLY space -- so this reads the position after the
    transform, which is the one that matters.

    tol=None means the spec did not say, and the default is taken from the size
    of the instance rather than fixed in millimetres -- see CENTROID_TOL_FACTOR
    in the generator, whose two numbers these are. An instance is the only place
    the scale is knowable, since it is not known until the assembly is built.
    \"\"\"
    for name, x, y, z, tol in entries:
        if name not in a.instances.keys():
            message = ('EXPECT_PLACED: no instance called %s. Present: %s.'
                       % (name, ', '.join(sorted(a.instances.keys()))))
            _sel_log(message)
            raise ValueError(message)
        box = _sel_bbox(a.instances[name])
        low, high = box
        centre = ((low[0] + high[0]) / 2.0, (low[1] + high[1]) / 2.0,
                  (low[2] + high[2]) / 2.0)
        span = max(high[0] - low[0], high[1] - low[1], high[2] - low[2])
        stated = tol is not None
        if not stated:
            tol = max(_CENTROID_TOL_FLOOR, abs(span) * _CENTROID_TOL_FACTOR)
        off = (abs(centre[0] - x), abs(centre[1] - y), abs(centre[2] - z))
        if max(off) > tol:
            message = ('EXPECT_PLACED: instance %s sits at %s, the spec says '
                       '(%s, %s, %s) within %s%s. Off by %s.'
                       % (name, centre, x, y, z, tol,
                          '' if stated else (' (default, from a span of %s)'
                                             % span), off))
            _sel_log(message)
            raise ValueError(message)
        # The margin is logged on the way past so that "how close did a passing
        # spec come to being refused" is a number somebody can read, not a thing
        # to be guessed at the next time this tolerance is touched.
        _sel_log('EXPECT_OK: %s at %s, off by %.6g of %.6g allowed'
                 % (name, centre, max(off), tol))


'''

# mesh -- cut, mesh quality, mesh coverage
_H_MESH = '''\
def _cut(model, p, part_name, sketch_id, depth):
    \"\"\"Cut a profile through the part from its top face, and prove it worked.

    Every line here is a measured fact rather than a reading of the manual.
    Measured on Abaqus 2021, cutting an asymmetric r=4 hole at (12, 20) in a
    60 x 100 x 5 plate:

      * CutExtrude without a sketch transform raises "Cut extrude feature
        failed". The transform is mandatory, and the sketch has to be built
        with transform= from the start -- which is why the profile is replayed
        here instead of reusing the sketch object the spec drew.
      * findAt(coordinates=(...)) returns a SEQUENCE, and face.getEdges()
        returns edge INDICES, not edge objects. Both were being passed straight
        into CutExtrude, which is why this path had never once run.
      * sketchUpEdge decides how sketch coordinates map to global ones, and
        getting it wrong FAILS SILENTLY. On the top face, edges 0 and 2 gave
        the hole at (12, 20); edges 1 and 3 produced no hole at all, unchanged
        volume, no exception. On the bottom face, edge 1 produced a real hole
        of the right radius at (20, 12) -- x and y transposed, same volume,
        same element count, and every symmetric test case in the world would
        have passed it.

    There is no way to know the right edge from the spec: it depends on the
    face's topology, which changes with every previous cut. So try them and
    check. The check is the point -- not the loop.
    \"\"\"
    profile = _SKETCHES.get((part_name, sketch_id))
    if profile is None:
        raise ValueError('CUT_NO_SKETCH: %s asked to cut with sketch %r, which '
                         'was never drawn.' % (part_name, sketch_id))
    circles = profile['circles']
    if not circles:
        raise ValueError('CUT_NOT_SUPPORTED: %s asked to cut with sketch %r, a '
                         'rectangle. Only circular cuts have a geometry check '
                         'behind them, and a cut that cannot be checked is a '
                         'cut that can silently miss.' % (part_name, sketch_id))

    plane = _sel_resolve(p, 'faces', 'z', 'max', '=1',
                         '%s top face (cut plane)' % part_name, 1.0e-4)[0]
    z_top = plane.pointOn[0][2]

    # A circular edge cannot orient a sketch. getRadius() raising is how a
    # straight edge identifies itself -- there is no predicate for it.
    candidates = []
    for edge_index in plane.getEdges():
        edge = p.edges[edge_index]
        try:
            edge.getRadius()
        except Exception:
            candidates.append(edge_index)
    if not candidates:
        raise ValueError('CUT_NO_STRAIGHT_EDGE: the top face of %s has no '
                         'straight edge to orient the sketch against.'
                         % part_name)

    problems = []
    for attempt_no, edge_index in enumerate(candidates):
        before = set(p.features.keys())
        sketch_name = '_cut_%s_%s_%d' % (part_name, sketch_id, attempt_no)
        try:
            edge = p.edges[edge_index]
            transform = p.MakeSketchTransform(
                sketchPlane=plane, sketchUpEdge=edge, sketchPlaneSide=SIDE1,
                sketchOrientation=RIGHT, origin=(0.0, 0.0, z_top))
            sketch = model.ConstrainedSketch(
                name=sketch_name, sheetSize=400.0, gridSpacing=10.0,
                transform=transform)
            for cx, cy, r in circles:
                sketch.CircleByCenterPerimeter(center=(cx, cy),
                                               point1=(cx + r, cy))
            p.CutExtrude(sketchPlane=plane, sketchUpEdge=edge,
                         sketchPlaneSide=SIDE1, sketchOrientation=RIGHT,
                         sketch=sketch, depth=depth, flipExtrudeDirection=OFF)
        except Exception:
            problems.append('edge %d: %s' % (edge_index, sys.exc_info()[1]))
            _cut_rollback(p, before)
            continue

        missing = _cut_missing(p, circles)
        if not missing:
            _sel_log('CUT_OK: %s cut %d circle(s) from sketch %r using edge %d'
                     % (part_name, len(circles), sketch_id, edge_index))
            return
        problems.append('edge %d: %s' % (edge_index, '; '.join(missing)))
        _cut_rollback(p, before)

    message = ('CUT_FAILED: %s could not cut sketch %r where the spec asked. '
               'Tried %d orientation(s): %s'
               % (part_name, sketch_id, len(candidates), ' | '.join(problems)))
    _sel_log(message)
    raise ValueError(message)


def _mesh_diagnosis(p):
    \"\"\"Why a part would not mesh, asked of Abaqus rather than guessed.

    Measured on Abaqus 2021: getMeshControl(region=cell, attribute=TECHNIQUE)
    answers UNMESHABLE for a cell that cannot be meshed with the controls
    currently set -- BEFORE generateMesh is called, and without it. On the
    bolted housing it reads UNMESHABLE under HEX and FREE under TET, which is
    the whole difference between "this part is impossible" and "you asked for
    hexes on a shape that has none".

    Worth saying plainly: HEX + SYSTEM_ASSIGN is ACCEPTED on that part, meshes
    nothing, and raises nothing. So a message that only says "no elements" is
    describing the symptom.
    \"\"\"
    lines = []
    for i, cell in enumerate(p.cells):
        try:
            shape = p.getMeshControl(region=cell, attribute=ELEM_SHAPE)
            technique = p.getMeshControl(region=cell, attribute=TECHNIQUE)
        except Exception:
            continue
        lines.append('cell %d: %s/%s' % (i, shape, technique))
    if not lines:
        return ''
    return ' Mesh controls now: %s.' % '; '.join(lines)


def _mesh_worst(p, name):
    \"\"\"The worst value of one criterion, or None when it does not report one.

    ANALYSIS_CHECKS answers with element lists and no `worst`; the shape
    measures answer with worst / average / worstElement and no lists. Nothing
    in the API says which you get, so both are handled.
    \"\"\"
    constant = globals().get(name)
    if constant is None:
        return None, None, None
    try:
        report = p.verifyMeshQuality(criterion=constant)
    except Exception:
        return None, None, None
    worst = float(report['worst']) if 'worst' in report else None
    return worst, len(report.get('naElements', ())), int(report['numElements'])


def _mesh_quality(p, part_name, rows):
    \"\"\"The criteria the spec named, and the bound it put on each.

    Two things are measured here that the solver's own analysis checks do not
    see, both on Abaqus 2021:

    Shape. The same 10x10x100 cantilever, C3D8I, tip load 100 N:

        80 elements, 5 mm cubes        aspect  1.0   tip -1.31% vs theory
        2000 elements, 0.5x0.5x20      aspect 40.0   tip -5.18%
        2160 elements, 1.67 mm cubes   aspect  1.0   tip -0.84%

    All three pass ANALYSIS_CHECKS with 0 failed and 0 warned. The middle one
    costs the same as the last one and is six times further from the answer,
    and it is the one that looks best in a log line that only prints a count.

    Coverage. `naElements` is the elements a criterion does not apply to, and a
    criterion that applies to none of them still answers `failedElements: []`.
    Measured on that hex mesh: SHAPE_FACTOR reports 2160 of 2160 not
    applicable, MAX_FREQUENCY and STABLE_TIME_INCREMENT likewise, and
    GEOM_DEVIATION_FACTOR reports 928 of 2160 -- `worst: 0.0` while it never
    looked at 43% of the mesh. So a pass is only worth anything alongside the
    coverage, and that is why na has to be zero unless the spec says otherwise.
    \"\"\"
    for row in rows:
        name = row['criterion']
        constant = globals().get(name)
        if constant is None:
            _expect_fail(
                'QUALITY_UNKNOWN: part %s asks for criterion %s, which this '
                'release does not have.' % (part_name, name))
        kwargs = dict(row.get('kwargs') or {})
        kwargs['criterion'] = constant
        try:
            report = p.verifyMeshQuality(**kwargs)
        except Exception:
            _expect_fail('QUALITY_REFUSED: part %s criterion %s -> %s'
                         % (part_name, name, str(sys.exc_info()[1])))

        total = int(report['numElements'])
        na = len(report.get('naElements', ()))
        if na and not row.get('allow_na'):
            _expect_fail(
                'QUALITY_NOT_APPLICABLE: part %s asked for %s and Abaqus does '
                'not apply it to %d of %d element(s). It still answers with an '
                'empty failure list for the rest, so a pass here would mean '
                'nothing -- measured, SHAPE_FACTOR on a hex mesh is 100%% not '
                'applicable and reports 0 failed. Name a criterion that covers '
                'these elements, or write `allow_na: true` to say the gap is '
                'understood.' % (part_name, name, na, total))

        worst = float(report['worst']) if 'worst' in report else None
        for key in ('max', 'min'):
            if row.get(key) is None:
                continue
            if worst is None:
                _expect_fail(
                    'QUALITY_NO_WORST: part %s bounds %s with `%s`, but %s '
                    'answers with element lists and no worst value. Bound it '
                    'with `threshold:` and `max_failed:` instead.'
                    % (part_name, name, key, name))
            if key == 'max' and worst > row['max']:
                _expect_fail(
                    'QUALITY_WORSE: part %s has %s = %g, the spec allows at '
                    'most %g.' % (part_name, name, worst, row['max']))
            if key == 'min' and worst < row['min']:
                _expect_fail(
                    'QUALITY_WORSE: part %s has %s = %g, the spec wants at '
                    'least %g.' % (part_name, name, worst, row['min']))

        if row.get('max_failed') is not None:
            if 'failedElements' not in report:
                _expect_fail(
                    'QUALITY_NO_COUNT: part %s asks for max_failed on %s, '
                    'which reports no failedElements at this threshold.'
                    % (part_name, name))
            failed = len(report['failedElements'])
            if failed > row['max_failed']:
                _expect_fail(
                    'QUALITY_FAILED: part %s has %d of %d element(s) failing '
                    '%s, the spec allows %d.'
                    % (part_name, failed, total, name, row['max_failed']))

        detail = []
        if worst is not None:
            detail.append('worst=%g' % worst)
        if 'failedElements' in report:
            detail.append('failed=%d' % len(report['failedElements']))
        if na:
            detail.append('n/a=%d of %d' % (na, total))
        _sel_log('QUALITY_OK: %s %s %s'
                 % (part_name, name, ' '.join(detail) or 'measured'))


def _mesh_check(p, part_name, elements_expect=None, max_warned=None,
                quality=None, nodes_expect=None):
    \"\"\"Refuse a mesh that exists but cannot be trusted.

    The old check was len(p.elements) == 0, which only catches the case where
    meshing produced nothing at all. Everything between that and a good mesh
    was accepted: a region left unmeshed (Abaqus meshes what it can and moves
    on), or elements that fail its own analysis checks. Both give a job that
    solves and a stress that is wrong by an amount nobody can see.

    verifyMeshQuality(ANALYSIS_CHECKS) returns the solver's own verdict --
    measured on Abaqus 2021 it hands back numElements / warningElements /
    failedElements / naElements. What it does NOT return is any measure of
    shape: a mesh of aspect ratio 40 passes it with nothing flagged, which is
    what _mesh_quality is for.
    \"\"\"
    if len(p.elements) == 0:
        _expect_fail(
            'MESH_EMPTY: part %s produced no elements.%s'
            % (part_name, _mesh_diagnosis(p)))

    unmeshed = p.getUnmeshedRegions()
    if unmeshed is not None:
        _expect_fail(
            'MESH_INCOMPLETE: part %s has regions Abaqus could not mesh. It '
            'meshes what it can and reports nothing, so the job would have run '
            'on a partial model.%s' % (part_name, _mesh_diagnosis(p)))

    report = p.verifyMeshQuality(criterion=ANALYSIS_CHECKS)
    failed = len(report.get('failedElements', ()))
    warned = len(report.get('warningElements', ()))
    na = len(report.get('naElements', ()))
    total = int(report['numElements'])
    if failed:
        _expect_fail(
            'MESH_BAD: part %s has %d element(s) that fail the solver own '
            'analysis checks, out of %d. Refine the seed or change the mesh '
            'technique.' % (part_name, failed, len(p.elements)))
    if total and na == total:
        _expect_fail(
            'MESH_UNCHECKED: part %s is meshed with %d element(s) the solver '
            'analysis checks do not apply to, so "0 failed" here was measured '
            'on nothing at all.' % (part_name, total))

    count = len(p.elements)
    if elements_expect is not None and not _sel_expect_ok(count, elements_expect):
        _expect_fail(
            'MESH_COUNT: part %s meshed to %d elements, the spec says %s. A '
            'mesh far coarser than intended still solves and still reports '
            'COMPLETED.' % (part_name, count, elements_expect))
    if max_warned is not None and warned > max_warned:
        _expect_fail(
            'MESH_WARNED: part %s has %d element(s) Abaqus flags as poor, the '
            'spec allows %d.' % (part_name, warned, max_warned))
    # The node count matters where the mesh was not made here. A part read out
    # of a deck has whatever the file held, and the element count alone does
    # not say which ORDER the elements are: measured on Abaqus 2021, the same
    # 80-element bar is 189 nodes as C3D8 and would be far more as C3D20. So a
    # spec that knows what it exported can state both.
    nodes = len(p.nodes)
    if nodes_expect is not None and not _sel_expect_ok(nodes, nodes_expect):
        _expect_fail(
            'MESH_NODES: part %s has %d node(s), the spec says %s. For a mesh '
            'read from a file this is what says the file that arrived is the '
            'file that was meant.' % (part_name, nodes, nodes_expect))

    if quality:
        _mesh_quality(p, part_name, quality)

    # The shape of the elements goes into the line whether or not the spec
    # asked, because "elems=2000 warnings=0" reads like the better of two
    # meshes when it is the worse one. Measured: 2000 slivers of aspect 40 are
    # 5.2% off where 2160 cubes are 0.8% off, at the same cost.
    aspect, aspect_na, _n = _mesh_worst(p, 'ASPECT_RATIO')
    shape = ''
    if aspect is not None:
        shape = ' aspect=%.3g' % aspect
        if aspect_na:
            shape += '(n/a=%d)' % aspect_na
    if na:
        shape += ' unchecked=%d' % na
    _sel_log('MESH_OK: %s nodes=%d elems=%d warnings=%d%s'
             % (part_name, len(p.nodes), count, warned, shape))


def _cut_rollback(p, before):
    for name in list(p.features.keys()):
        if name not in before:
            try:
                p.deleteFeatures(featureNames=(name,))
            except Exception:
                pass


def _cut_missing(p, circles):
    \"\"\"Which requested circles are not present in the part as real holes.

    A missed cut leaves the volume untouched and raises nothing; a transposed
    one leaves the volume EXACTLY right, so volume alone cannot decide this.
    The position has to be checked.

    Which measurement to check it WITH is itself measured. On Abaqus 2021, over
    holes of r = 4, 6, 12 and 50 cut through depths of 5 to 200 mm:

      * getRadius() is exact -- zero error in all five.
      * a point ON the face sits its own radius from the axis to 2.6e-07, i.e.
        float noise.
      * getCentroid() is a TESSELLATION ESTIMATE. It lands on the axis exactly
        at r = 4 and r = 6, and misses by 0.00901 at r = 12 and 0.02690 at
        r = 50 -- both about 5.4e-4 * r. The removed volume agreed with
        pi*r^2*h to seven digits in every case, so the cuts were exact and the
        instrument was not.

    An earlier version asked the centroid alone and allowed it r*1e-4, which is
    7.5x too tight at r = 12: it refused a bore that was in exactly the right
    place. So the sharp test is the radial one, and the centroid is kept as a
    coarse locator with a tolerance taken from the table above. Both must agree.
    \"\"\"
    found = []
    for f in p.faces:
        try:
            radius = f.getRadius()
        except Exception:
            continue
        centroid = f.getCentroid()[0]
        found.append((centroid[0], centroid[1], radius, f.pointOn[0]))
    missing = []
    for cx, cy, r in circles:
        # 4x the worst tessellation error measured above, and still three
        # orders below the millimetres a transposed hole moves by.
        centre_tol = max(1.0e-3, r * 2.0e-3)
        radial_tol = max(1.0e-5, r * 1.0e-6)
        hit = False
        nearest = None
        for fx, fy, fr, point_on in found:
            if abs(fr - r) > max(1.0e-6, r * 1.0e-6):
                continue
            radial = ((point_on[0] - cx) ** 2
                      + (point_on[1] - cy) ** 2) ** 0.5 - fr
            offset = max(abs(fx - cx), abs(fy - cy))
            if nearest is None or abs(radial) < abs(nearest[0]):
                nearest = (radial, offset)
            if abs(radial) <= radial_tol and offset <= centre_tol:
                hit = True
                break
        if not hit:
            detail = ''
            if nearest is not None:
                detail = (' Nearest face of that radius has a surface point %g '
                          'off the asked-for axis, and its centroid is %g away '
                          '(allowed %g).' % (nearest[0], nearest[1], centre_tol))
            missing.append('no r=%s hole at (%s, %s).%s' % (r, cx, cy, detail))
    return missing
'''

# Order is the contract.
_HELPERS = (
    _H_INTERACTIONS
    + _H_DISPATCH
    + _H_CREATION
    + _H_RESOLVERS
    + _H_DECK
    + _H_ASSEMBLY
    + _H_MESH
)

PREAMBLE = _PREAMBLE
HELPERS = _HELPERS
